___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

### Some Reminders on Exploratory data analysis (EDA)

Exploratory data analysis (EDA) is an especially important activity in the routine of a data analyst or scientist. It enables an in depth understanding of the dataset, define or discard hypotheses and create predictive models on a solid basis. It uses data manipulation techniques and several statistical tools to describe and understand the relationship between variables and how these can impact business. By means of EDA, we can obtain meaningful insights that can impact analysis under the following questions (If a checklist is good enough for pilots to use every flight, it‚Äôs good enough for data scientists to use with every dataset).
1. What question are you trying to solve (or prove wrong)?
2. What kind of data do you have?
3. What‚Äôs missing from the data?
4. Where are the outliers?
5. How can you add, change or remove features to get more out of your data?

**``Exploratory data analysis (EDA)``** is often an **iterative brainstorming process** where you pose a question, review the data, and develop further questions to investigate before beginning model development work. The image below shows how the brainstorming phase is connected with that of understanding the variables and how this in turn is connected again with the brainstorming phase.<br>

<img src=https://i.ibb.co/k0MC950/EDA-Process.png width="300" height="100">

[Image Credit: Andrew D.](https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee)

**``In this context, the project consists of 3 parts in general:``**
* **The first part** is related to 'Data Cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, and Dropping useless columns.
* **The second part** is related to 'Filling Data', in other words 'Imputation'. It deals with Missing Values. Categorical to numeric transformation is done as well.
* **The third part** is related to 'Handling Outliers of Data' via Visualization libraries. So, some insights will be extracted.

**``NOTE:``**  However, you are free to create your own style. You do NOT have to stick to the steps above. We, the DA & DV instructors, recommend you study each part separately to create a source notebook for each part title for your further studies. 

# PART- 1 Data Cleaning

### Importing Libraries

In [487]:
# import lineer algebra and data analysis library
import numpy as np
import pandas as pd

# import visualisation library
import matplotlib.pyplot as plt
from matplotlib import patches
import seaborn as sns

# import warning library to suppress warnings
import warnings

### Settings

In [488]:
# Suppressing a warning 
warnings.filterwarnings("ignore") 

# It is a magic function that renders the figure in the notebook
%matplotlib inline 

# Changing the figure size of a seaborn axes 
sns.set(rc={"figure.figsize": (10, 6)})

# The style parameters control properties like the color of the background and whether a grid is enabled by default.
sns.set_style("whitegrid")

# To display maximum columns
pd.set_option('display.max_columns', None)

# To display maximum rows
pd.set_option('display.max_rows', 100)

## Reading scout_car.json file as a dataframe named df

In [489]:
df = pd.read_json("scout_car/scout_car.json", lines=True)

### Creating a copy from df named df_copy

In [490]:
df_copy = df.copy()

## Checking the dataframe with head, tail and sample

In [491]:
# Checking the head of df

df.head()

url make_model  \
0  https://www.autoscout24.com//offers/audi-a1-sp...    Audi A1   
1  https://www.autoscout24.com//offers/audi-a1-1-...    Audi A1   
2  https://www.autoscout24.com//offers/audi-a1-sp...    Audi A1   
3  https://www.autoscout24.com//offers/audi-a1-1-...    Audi A1   
4  https://www.autoscout24.com//offers/audi-a1-sp...    Audi A1   

                                   short_description body_type  price  \
0        Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770   
1                                     1.8 TFSI sport    Sedans  14500   
2  Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640   
3                            1.4 TDi Design S tronic    Sedans  14500   
4  Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790   

                vat         km registration         prev_owner  kW      hp  \
0    VAT deductible  56,013 km      01/2016  2 previous owners NaN   66 kW   
1  Price negotiable  80,000 km      03/2017               None NaN  141 kW   
2    VAT deductible  83,450 km      02/2016   1 previous owner NaN   85 kW   
3              None  73,000 km      08/2016   1 previous owner NaN   66 kW   
4              None  16,200 km      05/2016   1 previous owner NaN   66 kW   

                                      Type Previous Owners  \
0  [, Used, , Diesel (Particulate Filter)]           \n2\n   
1                     [, Used, , Gasoline]             NaN   
2  [, Used, , Diesel (Particulate Filter)]           \n1\n   
3  [, Used, , Diesel (Particulate Filter)]           \n1\n   
4  [, Used, , Diesel (Particulate Filter)]           \n1\n   

                         Next Inspection                      Inspection new  \
0  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]   
1                                    NaN                                 NaN   
2                                    NaN                                 NaN   
3                                    NaN                                 NaN   
4                                    NaN  [\nYes\n, \n109 g CO2/km (comb)\n]   

                           Warranty                      Full Service  \
0           [\n, \n, \n4 (Green)\n]                          [\n, \n]   
1                               NaN                               NaN   
2  [\n, \n, \n99 g CO2/km (comb)\n]                               NaN   
3                               NaN  [\n, \n, \n99 g CO2/km (comb)\n]   
4              [\n, \n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   

    Non-smoking Vehicle null      Make         Model     Offer Number  \
0              [\n, \n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]   
1                   NaN   []  \nAudi\n  [\n, A1, \n]              NaN   
2                   NaN   []  \nAudi\n  [\n, A1, \n]   [\nAM-95365\n]   
3  [\n, \n, \nEuro 6\n]   []  \nAudi\n  [\n, A1, \n]              NaN   
4              [\n, \n]   []  \nAudi\n  [\n, A1, \n]      [\nC1626\n]   

  First Registration       Body Color      Paint Type  \
0     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]   
1     [\n, 2017, \n]    [\n, Red, \n]             NaN   
2     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]   
3     [\n, 2016, \n]  [\n, Brown, \n]  [\nMetallic\n]   
4     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]   

            Body Color Original          Upholstery              Body  \
0           [\nMythosschwarz\n]  [\nCloth, Black\n]  [\n, Sedans, \n]   
1                           NaN   [\nCloth, Grey\n]  [\n, Sedans, \n]   
2  [\nmythosschwarz metallic\n]  [\nCloth, Black\n]  [\n, Sedans, \n]   
3                           NaN                 NaN  [\n, Sedans, \n]   
4  [\nMythosschwarz Metallic\n]  [\nCloth, Black\n]  [\n, Sedans, \n]   

  Nr. of Doors Nr. of Seats      Model Code         Gearing Type  \
0      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]   
1      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]   
2      [\n4\n]      

In [492]:
# Checking the tail of df

df.tail()

url      make_model  \
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace   

                                       short_description body_type  price  \
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950   
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885   
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875   
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700   
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999   

                  vat        km registration        prev_owner  kW      hp  \
15914  VAT deductible      - km          -/-              None NaN  147 kW   
15915  VAT deductible  9,900 km      01/2019  1 previous owner NaN  165 kW   
15916  VAT deductible     15 km      03/2019  1 previous owner NaN  146 kW   
15917  VAT deductible     10 km      06/2019              None NaN  147 kW   
15918  VAT deductible      - km      01/2019  1 previous owner NaN  165 kW   

                                                    Type  \
15914             [, New, , Diesel (Particulate Filter)]   
15915  [, Used, , Super 95 / Super Plus 98 (Particula...   
15916                       [, Pre-registered, , Diesel]   
15917                       [, Pre-registered, , Diesel]   
15918                      [, Demonstration, , Super 95]   

                                         Previous Owners  \
15914                                                NaN   
15915  [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...   
15916                   [\n1\n, \n139 g CO2/km (comb)\n]   
15917                                                NaN   
15918                                              \n1\n   

                              Next Inspection  \
15914                                     NaN   
15915  [\n01/2022\n, \n168 g CO2/km (comb)\n]   
15916                                     NaN   
15917                                     NaN   
15918                                     NaN   

                           Inspection new                 Warranty  \
15914                                 NaN            \n24 months\n   
15915                                 NaN     [\n, \n, \nEuro 6\n]   
15916         [\nYes\n, \nEuro 6d-TEMP\n]  [\n, \n, \n4 (Green)\n]   
15917                                 NaN                       \n   
15918  [\nYes\n, \n153 g CO2/km (comb)\n]                      NaN   

      Full Service      Non-smoking Vehicle null         Make  \
15914          NaN                      NaN   []  \nRenault\n   
15915          NaN  [\n, \n, \n4 (Green)\n]   []  \nRenault\n   
15916     [\n, \n]                 [\n, \n]   []  \nRenault\n   
15917          NaN                      NaN   []  \nRenault\n   
15918          NaN                      NaN   []  \nRenault\n   

                  Model          Offer Number First Registration  \
15914  [\n, Espace, \n]        [\n10988301\n]                NaN   
15915  [\n, Espace, \n]     [\n507370_3223\n]     [\n, 2019, \n]   
15916  [\n, Espace, \n]        [\nEspace16\n]     [\n, 2019, \n]   
15917  [\n, Espace, \n]         [\n2691331\n]     [\n, 2019, \n]   
15918  [\n, Espace, \n]  [\nRe_30000008029\n]     [\n, 2019, \n]   

            Body Color      Paint Type           Body Color Original  \
15914   [\n, Grey, \n]  [\nMetallic\n]            [\nGrigio scuro\n]   
15915   [\n, Grey, \n]  [\nMetallic\n]     [\nStahl-Grau Metallic\n]   
15916  [\n, White, \n]             NaN             [\narktis-wei√ü\n]   
15917   [\n, Grey, \n]             NaN                  [\nGrigio\n]   
15918   [\n, Grey, \n]  [\nMetallic\n]  [\nTitanium-Grau Metallic

In [493]:
# Checking the df by taking samples

df.sample(10)

url     make_model  \
3307   https://www.autoscout24.com//offers/audi-a3-sp...        Audi A3   
4282   https://www.autoscout24.com//offers/audi-a3-sp...        Audi A3   
10796  https://www.autoscout24.com//offers/opel-insig...  Opel Insignia   
12882  https://www.autoscout24.com//offers/opel-insig...  Opel Insignia   
6051   https://www.autoscout24.com//offers/opel-astra...     Opel Astra   
4947   https://www.autoscout24.com//offers/audi-a3-li...        Audi A3   
9471   https://www.autoscout24.com//offers/opel-corsa...     Opel Corsa   
9582   https://www.autoscout24.com//offers/opel-corsa...     Opel Corsa   
2079   https://www.autoscout24.com//offers/audi-a1-sp...        Audi A1   
8528   https://www.autoscout24.com//offers/opel-corsa...     Opel Corsa   

                                       short_description      body_type  \
3307                          SPB 1.6 TDI S tronic Sport         Sedans   
4282                               Sportback Dsl 1.6 TDi         Sedans   
10796            1,6 CDTI SportsTouNAVI,AppleCarplay,EU6  Station wagon   
12882  Sports Tourer Innovation - Nieuw!! - 1.6 CDTi ...  Station wagon   
6051                   1.6 D (CDTI) Automatik Innovation         Sedans   
4947      Limousine 1.6 TDI design Navi/LED/SitzHzg/PDC+         Sedans   
9471           1.4 Color Edition *PDC*I-LINK*/ 31555-467        Compact   
9582                                    BICOLOR 1,4 75CV         Sedans   
2079            Sportback 30 TFSI Advanced S-Tronic 85 k         Sedans   
8528        E 3tg 1.4 AT Edition IntelliLink 2J Garantie         Sedans   

       price               vat          km registration         prev_owner  \
3307   20000              None   57,000 km      09/2016               None   
4282   17899    VAT deductible   29,500 km      06/2017               None   
10796  10990    VAT deductible  101,600 km      10/2016   1 previous owner   
12882  31318    VAT deductible        - km          -/-               None   
6051   10350  Price negotiable  127,000 km      03/2016  2 previous owners   
4947   20398    VAT deductible   13,812 km      06/2018   1 previous owner   
9471    8950    VAT deductible   41,400 km      03/2017   1 previous owner   
9582    9300    VAT deductible   29,497 km      01/2018   1 previous owner   
2079   26200    VAT deductible       50 km      03/2019               None   
8528   11980    VAT deductible   24,100 km      01/2018   1 previous owner   

       kW      hp                                               Type  \
3307  NaN   81 kW                                 [, Used, , Diesel]   
4282  NaN   81 kW                                 [, Used, , Diesel]   
10796 NaN  100 kW                                 [, Used, , Diesel]   
12882 NaN  100 kW                                 [, Used, , Diesel]   
6051  NaN  100 kW                                 [, Used, , Diesel]   
4947  NaN   85 kW  [, Employee's car, , Diesel (Particulate Filter)]   
9471  NaN   66 kW                               [, Used, , Super 95]   
9582  NaN   55 kW                     [, Employee's car, , Gasoline]   
2079  NaN   85 kW                               [, Used, , Gasoline]   
8528  NaN   66 kW                [, Used, , Super 95 / Super E10 95]   

      Previous Owners                                    Next Inspection  \
3307              NaN                                                NaN   
4282              NaN                                                NaN   
10796           \n1\n             [\n11/2020\n, \n135 g CO2/km (comb)\n]   
12882             NaN                                                NaN   
6051            \n2\n             [\n04/2021\n, \n115 g CO2/km (comb)\n]   
4947            \n1\n             [\n06/2021\n, \n107 g CO2/km (comb)\n]   
9471            \n1\n                                                NaN   
9582            \n1\n                                                NaN   
2079              NaN                                            

## Checking the summary information of df

In [494]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   url                            15919 non-null  object 
 1   make_model                     15919 non-null  object 
 2   short_description              15873 non-null  object 
 3   body_type                      15859 non-null  object 
 4   price                          15919 non-null  int64  
 5   vat                            11406 non-null  object 
 6   km                             15919 non-null  object 
 7   registration                   15919 non-null  object 
 8   prev_owner                     9091 non-null   object 
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object 
 11  Type                           15917 non-null  object 
 12  Previous Owners                9279 non-null  

## Checking the null values of df

In [495]:
df.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
Type                                 2
Previous Owners                   6640
Next Inspection                  12384
Inspection new                   11987
Warranty                          5420
Full Service                      7704
Non-smoking Vehicle               8742
null                                 0
Make                                 0
Model                                0
Offer Number                      3175
First Registration                1597
Body Color                         597
Paint Type                        5772
Body Color Original      

## Checking the duplicated values in df

In [496]:
# df.duplicated()

# As there is list type values in the columns, duplicated method didn't work.
# After fixing the list type values, duplicated values will be check.

## Cleaning column names

Column names was cleaned using skimpy library clean_columns method.

In [497]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type',
       'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty',
       'Full Service', 'Non-smoking Vehicle', 'null', 'Make', 'Model',
       'Offer Number', 'First Registration', 'Body Color', 'Paint Type',
       'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors',
       'Nr. of Seats', 'Model Code', 'Gearing Type', 'Displacement',
       'Cylinders', 'Weight', 'Drive chain', 'Fuel', 'Consumption',
       'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n',
       '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n',
       'description', 'Emission Label', 'Gears', 'Country version',
       'Electricity consumption', 'Last Service Date', 'Other Fuel Types',
       'Availability', 'Last Timing Belt Service Date', 'Available from'],
      dtype='object')

In [498]:
# Importing skimpy clean_columns method

from skimpy import clean_columns

In [499]:
# Cleaning column names using skimpy clean_columns method

df= clean_columns(df)

42 column names have been cleaned

## Checking the number of unique values in df

In [500]:
# df.nunique()  # As some columns values are in the form of list, this code raised with "TypeError: unhashable type: 'list'" error.

While checking the unique values in df, it has been determined that the data in some columns are in the form of a list. For this reason, it was decided to convert the data of the columns containing the list into strings, before applying the string methods in order to clean data.


## Changing data types of columns containing list type values to string

In [501]:
# Changing data types of columns containing list type values to string

df = df.applymap(lambda x: ','.join(map(str, x)) if isinstance(x, list) else x)
df

url      make_model  \
0      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
1      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
2      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
3      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
4      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
...                                                  ...             ...   
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace   

                                       short_description body_type  price  \
0            Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770   
1                                         1.8 TFSI sport    Sedans  14500   
2      Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640   
3                                1.4 TDi Design S tronic    Sedans  14500   
4      Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790   
...                                                  ...       ...    ...   
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950   
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885   
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875   
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700   
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999   

                    vat         km registration         prev_owner  k_w  \
0        VAT deductible  56,013 km      01/2016  2 previous owners  NaN   
1      Price negotiable  80,000 km      03/2017               None  NaN   
2        VAT deductible  83,450 km      02/2016   1 previous owner  NaN   
3                  None  73,000 km      08/2016   1 previous owner  NaN   
4                  None  16,200 km      05/2016   1 previous owner  NaN   
...                 ...        ...          ...                ...  ...   
15914    VAT deductible       - km          -/-               None  NaN   
15915    VAT deductible   9,900 km      01/2019   1 previous owner  NaN   
15916    VAT deductible      15 km      03/2019   1 previous owner  NaN   
15917    VAT deductible      10 km      06/2019               None  NaN   
15918    VAT deductible       - km      01/2019   1 previous owner  NaN   

           hp                                               type  \
0       66 kW                 ,Used,,Diesel (Particulate Filter)   
1      141 kW                                    ,Used,,Gasoline   
2       85 kW                 ,Used,,Diesel (Particulate Filter)   
3       66 kW                 ,Used,,Diesel (Particulate Filter)   
4       66 kW                 ,Used,,Diesel (Particulate Filter)   
...       ...                                                ...   
15914  147 kW                  ,New,,Diesel (Particulate Filter)   
15915  165 kW  ,Used,,Super 95 / Super Plus 98 (Particulate F...   
15916  146 kW                            ,Pre-registered,,Diesel   
15917  147 kW                            ,Pre-registered,,Diesel   
15918  165 kW                           ,Demonstration,,Super 95   

                                         previous_owners  \
0                                                  \n2\n   
1                                                    NaN   
2                                                  \n1\n   
3                                                  \n1\n   
4                                                  \n1\n   
...                                                  ...   
15914                                                NaN   
15915  \n1\n,\n,7

## Checking duplicated values after fixing data types

In [502]:
# Checking duplicated values in df after fixing list type values

df.duplicated().sum()

0

## Checking the nuniques in columns

In [504]:
df.nunique()

url                              15919
make_model                           9
short_description                10001
body_type                            9
price                             2956
vat                                  2
km                                6690
registration                        48
prev_owner                           4
k_w                                  0
hp                                  81
type                               169
previous_owners                    101
next_inspection                   1384
inspection_new                     201
warranty                           507
full_service                       122
non_smoking_vehicle                 94
null                                 1
make                                 3
model                                9
offer_number                     11440
first_registration                   4
body_color                          14
paint_type                           3
body_color_original      

## Defining a function to check null values, number of uniques and value counts for each column

In [505]:
def first_look(col):
    print('column name : ', col)
    print('--------------------------------')
    print('Percent_of_Nulls   : ', '%', round(df[col].isnull().sum() / df.shape[0]*100, 2))
    print('Number_of_Nulls   : ', df[col].isnull().sum())
    print('Number_of_Uniques : ', df[col].nunique())
    print("Value_counts :\n",df[col].value_counts(dropna = False))
    print()
    print("Value_counts with sort index :\n",df[col].value_counts(dropna = False).sort_index())
    print("##"*20)
    print()

In [506]:
# Checking the informations for each column using defined function first_look

for col in df.columns :
    first_look(col)

column name :  url
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  15919
Value_counts :
 https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e                  1
https://www.autoscout24.com//offers/opel-insignia-bus-inno-2-0-cdti-aut-navi-bi-xe-led-e6-diesel-black-8710b253-dd98-4ed0-9d46-cbad2d79532b                1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-10b7463b-9f56-4348-af35-df3432b2b585    1
https://www.autoscout24.com//offers/opel-insignia-2-0cdti-st-business-innovation-navi-bt-diesel-black-ba5a3368-dedc-4e51-9127-3976b26e93c2                 1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-7b52f054-78d3-4d5e-9370-8a7d081d7edd    1
                                                                     

Value_counts :
 NaN                                    12384
\n04/2022\n                               62
\n06/2021\n                               47
\n03/2021\n                               39
\n03/2022\n                               36
                                       ...  
\n06/2021\n,\n121 g CO2/km (comb)\n        1
\n02/2020\n,\n139 g CO2/km (comb)\n        1
\n10/2021\n,\n136 g CO2/km (comb)\n        1
\n06/2019\n,\n139 g CO2/km (comb)\n        1
\n01/2022\n,\n168 g CO2/km (comb)\n        1
Name: next_inspection, Length: 1385, dtype: int64

Value_counts with sort index :
 \n01/1921\n,\n120 g CO2/km (comb)\n        1
\n01/1955\n                                1
\n01/1999\n                                1
\n01/2001\n,\n120 g CO2/km (comb)\n        1
\n01/2001\n,\n122 g CO2/km (comb)\n        2
                                       ...  
\n12/2021\n,\n153 g CO2/km (comb)\n        4
\n12/2021\n,\n167 g CO2/km (comb)\n        1
\n12/2021\n,\nEuro 6\n                     1
\

Value_counts with sort index :
 \n2\n      116
\n3\n        1
\n4\n     1125
\n5\n    13336
\n6\n        2
\n7\n      362
NaN        977
Name: nr_of_seats, dtype: int64
########################################

column name :  model_code
--------------------------------
Percent_of_Nulls   :  % 68.73
Number_of_Nulls   :  10941
Number_of_Uniques :  232
Value_counts :
 NaN             10941
\n0035/BCB\n      268
\n0588/BNO\n      245
\n0588/BDB\n      206
\n0588/BHX\n      188
                ...  
\n0035/AVN\n        1
\n0035/BEM\n        1
\n0035/BAG\n        1
\n0035/BAA\n        1
\n3333/BKG\n        1
Name: model_code, Length: 233, dtype: int64

Value_counts with sort index :
 \n0000/000\n       21
\n0000/035\n        1
\n0000/ACP\n        1
\n0035/AAA\n        1
\n0035/AAD\n        1
                ...  
\n3333/BJR\n       79
\n3333/BKG\n        1
\n3333/BKQ\n       18
\n3333/BKR\n        8
NaN             10941
Name: model_code, Length: 233, dtype: int64
###########################

Number_of_Uniques :  12874
Value_counts :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

## First cleaning of df

There are so many strange values that should be cleaned.

Firstly, "\n" character will be cleaned.

In [507]:
# Cleaning "\n" character and strip "," character from both side in df columns

df= df.apply(lambda x: x.str.replace("\n","").str.strip(",") if x.dtype == "O" else x)
df

url      make_model  \
0      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
1      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
2      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
3      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
4      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
...                                                  ...             ...   
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace   

                                       short_description body_type  price  \
0            Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770   
1                                         1.8 TFSI sport    Sedans  14500   
2      Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640   
3                                1.4 TDi Design S tronic    Sedans  14500   
4      Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790   
...                                                  ...       ...    ...   
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950   
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885   
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875   
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700   
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999   

                    vat         km registration         prev_owner  k_w  \
0        VAT deductible  56,013 km      01/2016  2 previous owners  NaN   
1      Price negotiable  80,000 km      03/2017               None  NaN   
2        VAT deductible  83,450 km      02/2016   1 previous owner  NaN   
3                  None  73,000 km      08/2016   1 previous owner  NaN   
4                  None  16,200 km      05/2016   1 previous owner  NaN   
...                 ...        ...          ...                ...  ...   
15914    VAT deductible       - km          -/-               None  NaN   
15915    VAT deductible   9,900 km      01/2019   1 previous owner  NaN   
15916    VAT deductible      15 km      03/2019   1 previous owner  NaN   
15917    VAT deductible      10 km      06/2019               None  NaN   
15918    VAT deductible       - km      01/2019   1 previous owner  NaN   

           hp                                               type  \
0       66 kW                  Used,,Diesel (Particulate Filter)   
1      141 kW                                     Used,,Gasoline   
2       85 kW                  Used,,Diesel (Particulate Filter)   
3       66 kW                  Used,,Diesel (Particulate Filter)   
4       66 kW                  Used,,Diesel (Particulate Filter)   
...       ...                                                ...   
15914  147 kW                   New,,Diesel (Particulate Filter)   
15915  165 kW  Used,,Super 95 / Super Plus 98 (Particulate Fi...   
15916  146 kW                             Pre-registered,,Diesel   
15917  147 kW                             Pre-registered,,Diesel   
15918  165 kW                            Demonstration,,Super 95   

                                         previous_owners  \
0                                                      2   
1                                                    NaN   
2                                                      1   
3                                                      1   
4                                                      1   
...                                                  ...   
15914                                                NaN   
15915  1,,7.4 l/1

### Checking columns with first_look function after first cleaning of df 

In [508]:
# Checking the informations for each column using defined function first_look

for col in df.columns :
    first_look(col)

column name :  url
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  15919
Value_counts :
 https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e                  1
https://www.autoscout24.com//offers/opel-insignia-bus-inno-2-0-cdti-aut-navi-bi-xe-led-e6-diesel-black-8710b253-dd98-4ed0-9d46-cbad2d79532b                1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-10b7463b-9f56-4348-af35-df3432b2b585    1
https://www.autoscout24.com//offers/opel-insignia-2-0cdti-st-business-innovation-navi-bt-diesel-black-ba5a3368-dedc-4e51-9127-3976b26e93c2                 1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-7b52f054-78d3-4d5e-9370-8a7d081d7edd    1
                                                                     

Value_counts :
 NaN                                                                          5420
Euro 6                                                                       1868
                                                                             1343
12 months                                                                    1305
24 months                                                                     585
                                                                             ... 
2 months                                                                        1
72 months,125 g CO2/km (comb)                                                   1
60 months,14 g CO2/km (comb)                                                    1
24 months,121 g CO2/km (comb)                                                   1
36 months,,7.4 l/100 km (comb),,9.6 l/100 km (city),,6 l/100 km (country)       1
Name: warranty, Length: 507, dtype: int64

Value_counts with sort index :
        

Value_counts with sort index :
 Alloy wheels                                                                                            3245
Alloy wheels,Cab or rented Car                                                                            32
Alloy wheels,Cab or rented Car,Catalytic Converter                                                        15
Alloy wheels,Cab or rented Car,Catalytic Converter,Roof rack                                               1
Alloy wheels,Cab or rented Car,Catalytic Converter,Roof rack,Shift paddles,Sport seats,Voice Control       1
                                                                                                        ... 
Tuned car,Voice Control                                                                                    1
Voice Control                                                                                             85
Voice Control,Winter tyres                                                                      

## Checking the descriptive values of df

### Checking the descriptive values of object columns

In [509]:
df.describe(include='O').T

count unique  \
url                            15919  15919   
make_model                     15919      9   
short_description              15873  10001   
body_type                      15859      9   
vat                            11406      2   
km                             15919   6690   
registration                   15919     48   
prev_owner                      9091      4   
hp                             15919     81   
type                           15917    169   
previous_owners                 9279    101   
next_inspection                 3535   1384   
inspection_new                  3932    201   
warranty                       10499    506   
full_service                    8215    121   
non_smoking_vehicle             7177     93   
null                           15919      1   
make                           15919      3   
model                          15919      9   
offer_number                   12744  11440   
first_registration             14322      4   
body_color                     15322     14   
paint_type                     10147      3   
body_color_original            12160   1927   
upholstery                     12199     46   
body                           15859      9   
nr_of_doors                    15707      6   
nr_of_seats                    14942      6   
model_code                      4978    232   
gearing_type                   15919      3   
displacement                   15423     77   
cylinders                      10239      7   
weight                          8945    434   
drive_chain                     9061      3   
fuel                           15919     77   
consumption                    14013    881   
co_2_emission                  14111    123   
emission_class                 12898      7   
comfort_&_convenience          14999   6198   
entertainment_&_media          14545    346   
extras                         12957    659   
safety_&_security              14937   4443   
description                    15919  12864   
emission_label                  3985      6   
gears                          11207     10   
country_version                 7586     23   
electricity_consumption          137      1   
last_service_date                566    255   
other_fuel_types                 880      1   
availability                     635     15   
last_timing_belt_service_date     16     15   
available_from                   272     46   

                                                                             top  \
url                            https://www.autoscout24.com//offers/audi-a1-sp...   
make_model                                                               Audi A3   
short_description                              SPB 1.6 TDI 116 CV S tronic Sport   
body_type                                                                 Sedans   
vat                                                               VAT deductible   
km                                                                         10 km   
registration                                                                 -/-   
prev_owner                                                      1 previous owner   
hp                                                                         85 kW   
type                                           Used,,Diesel (Particulate Filter)   
previous_owners                                                                1   
next_inspection                                                          04/2022   
inspection_new                                                        Yes,Euro 6   
warranty                                                                  Euro 6   
full_service                                                           4 (Green)   
non_smoking_vehicle                                                                
null                                                                               
make                       

### Checking the descriptive values of numeric columns

In [510]:
df.describe(exclude="O").T

count          mean          std   min      25%      50%      75%  \
price  15919.0  18019.896727  7386.169409  13.0  12850.0  16900.0  21900.0   
k_w        0.0           NaN          NaN   NaN      NaN      NaN      NaN   

           max  
price  74600.0  
k_w        NaN

## First conclusion about df after checking the first_look results and descriptive values of each column 

After checking the first_look results and descriptive values of each column, it was decided

   * to replace empty rows with np.nan
   
   * to replace "[],[],[]" values with np.nan
   
   * to drop columns containing greater than or equal %95 null values
   
   * to apply data cleaning column by column.

### Replacing empty rows with np.nan

In [511]:
# Checking columns having empty rows

df.isin(['']).sum()

url                                  0
make_model                           0
short_description                    0
body_type                            0
price                                0
vat                                  0
km                                   0
registration                         0
prev_owner                           0
k_w                                  0
hp                                   0
type                                 0
previous_owners                      0
next_inspection                      0
inspection_new                       0
warranty                          1343
full_service                      1985
non_smoking_vehicle               3717
null                             15919
make                                 0
model                                0
offer_number                         0
first_registration                   0
body_color                           0
paint_type                           0
body_color_original      

In [512]:
# replacing empty rows with np.nan (1st method)

df[df.isin([''])] = np.nan

In [513]:
# 2nd method to replace empty rows with np.nan

df.replace(to_replace=r'^\s*$', value=np.nan, regex=True).isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
k_w                              15919
hp                                   0
type                                 2
previous_owners                   6640
next_inspection                  12384
inspection_new                   11987
warranty                          6763
full_service                      9689
non_smoking_vehicle              12459
null                             15919
make                                 0
model                                0
offer_number                      3175
first_registration                1597
body_color                         597
paint_type                        5772
body_color_original      

### Replacing rows containing only empt list with np.nan

In [514]:
# Checking the columns having "[],[],[]" values

df.isin(['[],[],[]']).sum()

url                                0
make_model                         0
short_description                  0
body_type                          0
price                              0
vat                                0
km                                 0
registration                       0
prev_owner                         0
k_w                                0
hp                                 0
type                               0
previous_owners                    0
next_inspection                    0
inspection_new                     0
warranty                           0
full_service                       0
non_smoking_vehicle                0
null                               0
make                               0
model                              0
offer_number                       0
first_registration                 0
body_color                         0
paint_type                         0
body_color_original                0
upholstery                         0
b

In [515]:
# replacing rows containing "[],[],[]" with np.nan (1st method)

df[df.isin(['[],[],[]'])] = np.nan

In [516]:
# 2nd method to replace "[],[],[]" values with np.nan

df.replace(to_replace=r'\[\]', value=np.nan, regex=True)

url      make_model  \
0      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
1      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
2      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
3      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
4      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
...                                                  ...             ...   
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace   

                                       short_description body_type  price  \
0            Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770   
1                                         1.8 TFSI sport    Sedans  14500   
2      Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640   
3                                1.4 TDi Design S tronic    Sedans  14500   
4      Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790   
...                                                  ...       ...    ...   
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950   
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885   
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875   
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700   
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999   

                    vat         km registration         prev_owner  k_w  \
0        VAT deductible  56,013 km      01/2016  2 previous owners  NaN   
1      Price negotiable  80,000 km      03/2017               None  NaN   
2        VAT deductible  83,450 km      02/2016   1 previous owner  NaN   
3                  None  73,000 km      08/2016   1 previous owner  NaN   
4                  None  16,200 km      05/2016   1 previous owner  NaN   
...                 ...        ...          ...                ...  ...   
15914    VAT deductible       - km          -/-               None  NaN   
15915    VAT deductible   9,900 km      01/2019   1 previous owner  NaN   
15916    VAT deductible      15 km      03/2019   1 previous owner  NaN   
15917    VAT deductible      10 km      06/2019               None  NaN   
15918    VAT deductible       - km      01/2019   1 previous owner  NaN   

           hp                                               type  \
0       66 kW                  Used,,Diesel (Particulate Filter)   
1      141 kW                                     Used,,Gasoline   
2       85 kW                  Used,,Diesel (Particulate Filter)   
3       66 kW                  Used,,Diesel (Particulate Filter)   
4       66 kW                  Used,,Diesel (Particulate Filter)   
...       ...                                                ...   
15914  147 kW                   New,,Diesel (Particulate Filter)   
15915  165 kW  Used,,Super 95 / Super Plus 98 (Particulate Fi...   
15916  146 kW                             Pre-registered,,Diesel   
15917  147 kW                             Pre-registered,,Diesel   
15918  165 kW                            Demonstration,,Super 95   

                                         previous_owners  \
0                                                      2   
1                                                    NaN   
2                                                      1   
3                                                      1   
4                                                      1   
...                                                  ...   
15914                                                NaN   
15915  1,,7.4 l/1

### Drop columns containing greater than or equal %95 null values

As mentioned above, it was decided to drop columns having greater than or equal %95 null values.

In [517]:
# Checking columns having greater than or equal %95 null values

print(df.shape)
for col in df.columns :
    if (df[col].isnull().sum() / df.shape[0]*100 ) >= 95:
        print("Column_Name :", col)
        print('Percent_of_Nulls   : ', '%', round(df[col].isnull().sum() / df.shape[0]*100, 2))
        print("-"*25)

(15919, 54)
Column_Name : k_w
Percent_of_Nulls   :  % 100.0
-------------------------
Column_Name : null
Percent_of_Nulls   :  % 100.0
-------------------------
Column_Name : electricity_consumption
Percent_of_Nulls   :  % 99.14
-------------------------
Column_Name : last_service_date
Percent_of_Nulls   :  % 96.44
-------------------------
Column_Name : other_fuel_types
Percent_of_Nulls   :  % 100.0
-------------------------
Column_Name : availability
Percent_of_Nulls   :  % 96.01
-------------------------
Column_Name : last_timing_belt_service_date
Percent_of_Nulls   :  % 99.9
-------------------------
Column_Name : available_from
Percent_of_Nulls   :  % 98.29
-------------------------


In [518]:
# dropping columns having greater than or equal %95 null values

for col in df.columns :
    if (df[col].isnull().sum() / df.shape[0]*100 ) >= 95:
        df.drop(col, axis=1, inplace=True)

In [519]:
# checking the shape of df

print(df.shape)

(15919, 46)


## Data cleaning column by column  and fixing data types

In [520]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'hp', 'type', 'previous_owners',
       'next_inspection', 'inspection_new', 'warranty', 'full_service',
       'non_smoking_vehicle', 'make', 'model', 'offer_number',
       'first_registration', 'body_color', 'paint_type', 'body_color_original',
       'upholstery', 'body', 'nr_of_doors', 'nr_of_seats', 'model_code',
       'gearing_type', 'displacement', 'cylinders', 'weight', 'drive_chain',
       'fuel', 'consumption', 'co_2_emission', 'emission_class',
       'comfort_&_convenience', 'entertainment_&_media', 'extras',
       'safety_&_security', 'description', 'emission_label', 'gears',
       'country_version'],
      dtype='object')

### url column

In [522]:
first_look("url")

column name :  url
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  15919
Value_counts :
 https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e                  1
https://www.autoscout24.com//offers/opel-insignia-bus-inno-2-0-cdti-aut-navi-bi-xe-led-e6-diesel-black-8710b253-dd98-4ed0-9d46-cbad2d79532b                1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-10b7463b-9f56-4348-af35-df3432b2b585    1
https://www.autoscout24.com//offers/opel-insignia-2-0cdti-st-business-innovation-navi-bt-diesel-black-ba5a3368-dedc-4e51-9127-3976b26e93c2                 1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-7b52f054-78d3-4d5e-9370-8a7d081d7edd    1
                                                                     

In [523]:
# "url" column can be used to fill null values in other columns.
# For this reason it will be dropped after investigating other columns.

### make_model, make and model columns

In [524]:
# Checking the make_model column

first_look("make_model")

column name :  make_model
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  9
Value_counts :
 Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

Value_counts with sort index :
 Audi A1           2614
Audi A2              1
Audi A3           3097
Opel Astra        2526
Opel Corsa        2219
Opel Insignia     2598
Renault Clio      1839
Renault Duster      34
Renault Espace     991
Name: make_model, dtype: int64
########################################



In [525]:
# checking the "make_model","make","model" columns together

df[["make_model","make","model"]].sample(20)

make_model     make     model
1852         Audi A1     Audi        A1
11651  Opel Insignia     Opel  Insignia
10279     Opel Corsa     Opel     Corsa
11985  Opel Insignia     Opel  Insignia
6970      Opel Astra     Opel     Astra
13462   Renault Clio  Renault      Clio
7205      Opel Astra     Opel     Astra
12472  Opel Insignia     Opel  Insignia
970          Audi A1     Audi        A1
7689      Opel Astra     Opel     Astra
10033     Opel Corsa     Opel     Corsa
12580  Opel Insignia     Opel  Insignia
3857         Audi A3     Audi        A3
2997         Audi A3     Audi        A3
5489         Audi A3     Audi        A3
4508         Audi A3     Audi        A3
3963         Audi A3     Audi        A3
9830      Opel Corsa     Opel     Corsa
3341         Audi A3     Audi        A3
11951  Opel Insignia     Opel  Insignia

In [526]:
# checking null values of "make_model","make" and "model" columns

df[["make_model","make","model"]].isna().sum()

make_model    0
make          0
model         0
dtype: int64

In [527]:
# checking the value_counts of "make_model","make" and "model" columns

df[["make_model","make","model"]].value_counts()

make_model      make     model   
Audi A3         Audi     A3          3097
Audi A1         Audi     A1          2614
Opel Insignia   Opel     Insignia    2598
Opel Astra      Opel     Astra       2526
Opel Corsa      Opel     Corsa       2219
Renault Clio    Renault  Clio        1839
Renault Espace  Renault  Espace       991
Renault Duster  Renault  Duster        34
Audi A2         Audi     A2             1
dtype: int64

As it is seen from the results above "make_model","make" and "model" columns have same values. So it was decided to drop "make" and "model" columns.

In [528]:
# dropping "make" and "model" columns

df.drop(columns=["make", "model"], inplace=True)

In [529]:
df.shape

(15919, 44)

### short_description column

In [531]:
# Checking the short_description column

first_look("short_description")

column name :  short_description
--------------------------------
Percent_of_Nulls   :  % 0.29
Number_of_Nulls   :  46
Number_of_Uniques :  10001
Value_counts :
 SPB 1.6 TDI 116 CV S tronic Sport                 64
NaN                                               46
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
                                                  ..
K Sports Tourer Business **Navi*Voll**             1
1.0 Turbo ecoFLEX Automatic Elective Park Navi     1
1.6 CDTI Business *Navi*Automatik*Spurh.*          1
1.6 136 CV Automatica Navi E 6 Garanzia Full       1
TCe 225 EDC GPF LIM Deluxe Pano,RFK                1
Name: short_description, Length: 10002, dtype: int64

Value_counts with sort index :
  1,6 CDTI**NAVI*Klimaaut*Tempomat*EURO6*T√úV NEU     1
 1.4 75 cv5 porte b-color                           1
 1.4 TFSI Attraction (125 CV)                       6
 1.4 T

In [532]:
# "url" column can be used to fill null values in other columns.
# For this reason it will be dropped after investigating other columns.

### body_type and body columns

In [533]:
# Checking the body_type and body columns

first_look("body_type")

column name :  body_type
--------------------------------
Percent_of_Nulls   :  % 0.38
Number_of_Nulls   :  60
Number_of_Uniques :  9
Value_counts :
 Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

Value_counts with sort index :
 Compact          3153
Convertible         8
Coupe              25
Off-Road           56
Other             290
Sedans           7903
Station wagon    3553
Transporter        88
Van               783
NaN                60
Name: body_type, dtype: int64
########################################



In [534]:
# Checking the body_type column

first_look("body")

column name :  body
--------------------------------
Percent_of_Nulls   :  % 0.38
Number_of_Nulls   :  60
Number_of_Uniques :  9
Value_counts :
 Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body, dtype: int64

Value_counts with sort index :
 Compact          3153
Convertible         8
Coupe              25
Off-Road           56
Other             290
Sedans           7903
Station wagon    3553
Transporter        88
Van               783
NaN                60
Name: body, dtype: int64
########################################



In [535]:
# Checking the value_counts of body_type and body columns together

df[["body_type","body"]].value_counts(dropna=False)

body_type      body         
Sedans         Sedans           7903
Station wagon  Station wagon    3553
Compact        Compact          3153
Van            Van               783
Other          Other             290
Transporter    Transporter        88
NaN            NaN                60
Off-Road       Off-Road           56
Coupe          Coupe              25
Convertible    Convertible         8
dtype: int64

As it is seen from the results above "body_type" and "body" columns contains same values. So it was decided to drop "body" column. Also, there are 60 null values in body_type column.

In [536]:
# drop body column

df.drop(columns="body", inplace=True)

In [537]:
df.shape

(15919, 43)

In [538]:
# Null values will be worked in next notebook.

### price column

In [539]:
# Checking the price column

first_look("price")

column name :  price
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  2956
Value_counts :
 14990    154
15990    151
10990    139
15900    106
17990    102
        ... 
17559      1
17560      1
17570      1
17575      1
39875      1
Name: price, Length: 2956, dtype: int64

Value_counts with sort index :
 13       1
120      1
255      1
331      1
4950     1
        ..
64332    1
64900    1
67600    1
68320    1
74600    1
Name: price, Length: 2956, dtype: int64
########################################



price column is already clean and there isn't any null values.

In [540]:
# Checking the data type of price column

df.price.dtypes

dtype('int64')

In [541]:
# fixing data type

df["price"] = df.price.astype(float)

### vat column

In [542]:
df.vat

0          VAT deductible
1        Price negotiable
2          VAT deductible
3                    None
4                    None
               ...       
15914      VAT deductible
15915      VAT deductible
15916      VAT deductible
15917      VAT deductible
15918      VAT deductible
Name: vat, Length: 15919, dtype: object

In [543]:
# Checking the vat column

first_look("vat")

column name :  vat
--------------------------------
Percent_of_Nulls   :  % 28.35
Number_of_Nulls   :  4513
Number_of_Uniques :  2
Value_counts :
 VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

Value_counts with sort index :
 Price negotiable      426
VAT deductible      10980
NaN                  4513
Name: vat, dtype: int64
########################################



vat column is already clean. There are 4513 null values.

In [544]:
# Null values will be worked in next notebook.

### km column

In [545]:
# checking the km column

first_look("km")

column name :  km
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  6690
Value_counts :
 10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ... 
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64

Value_counts with sort index :
 - km         1024
0 km           19
1 km          367
1,000 km       46
1,001 km        4
             ... 
99,999 km       1
990 km          2
991 km          1
995 km          1
999 km          3
Name: km, Length: 6690, dtype: int64
########################################



There are "km" and "," characters that should be cleaned in km column.

In [546]:
# Cleaning "km" and "," characters in km column and fixing data type : 1st method

df["km"] = df.km.str.replace(",", "").str.extract(r"(\d+)").astype(float)

In [547]:
# Cleaning "km" and "," characters in km column and fixing data type : 2nd method

# df["km"] = df.km.str.strip(" km").str.replace(",", "").replace(r"-", np.nan, regex=True).astype(float)

In [548]:
# Checking the km columns' values after cleaning

first_look("km")

column name :  km
--------------------------------
Percent_of_Nulls   :  % 6.43
Number_of_Nulls   :  1024
Number_of_Uniques :  6689
Value_counts :
 10.0       1045
NaN        1024
1.0         367
5.0         170
50.0        148
           ... 
67469.0       1
43197.0       1
10027.0       1
35882.0       1
57.0          1
Name: km, Length: 6690, dtype: int64

Value_counts with sort index :
 0.0           19
1.0          367
2.0            6
3.0           33
4.0           15
            ... 
248000.0       1
260000.0       1
291800.0       1
317000.0       1
NaN         1024
Name: km, Length: 6690, dtype: int64
########################################



As it is seen from results given above, there are 1024 null values in km column.

### registration and first_registration columns

In [549]:
# Checking the registration column

first_look("registration")

column name :  registration
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  48
Value_counts :
 -/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64

Value_counts with sort index :
 -/-        159

In [550]:
# Checking the registration and first_registration columns together

df[["registration","first_registration"]].value_counts(dropna=False)

registration  first_registration
-/-           NaN                   1597
03/2018       2018                   695
02/2019       2019                   585
05/2018       2018                   572
03/2019       2019                   543
01/2019       2019                   541
04/2018       2018                   541
02/2018       2018                   539
03/2016       2016                   536
06/2018       2018                   532
04/2016       2016                   532
01/2018       2018                   511
04/2019       2019                   506
02/2016       2016                   472
03/2017       2017                   471
05/2016       2016                   459
06/2016       2016                   452
05/2019       2019                   440
06/2017       2017                   409
05/2017       2017                   404
07/2018       2018                   396
04/2017       2017                   380
01/2016       2016                   376
02/2017       2017      

As it is seen from the results above "registration" and "first_registration" columns have similar values. So it was decided to drop "registration" column.

In [551]:
# drop registration column

df.drop(columns="registration", inplace=True)

In [552]:
df.shape

(15919, 42)

In [553]:
# fixing data type

df["first_registration"] = df.first_registration.astype(float)

A new column in the name of age can be created using first_registration column values. After that first_registration column can be  dropped.

There are 1597 null values in first_registration column.

In [554]:
# Null values will be worked and age column will be created in next notebook.

### prev_owner and previous_owners columns

In [555]:
# Checking the prev_owner column

first_look("prev_owner")

column name :  prev_owner
--------------------------------
Percent_of_Nulls   :  % 42.89
Number_of_Nulls   :  6828
Number_of_Uniques :  4
Value_counts :
 1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

Value_counts with sort index :
 1 previous owner     8294
2 previous owners     778
3 previous owners      17
4 previous owners       2
NaN                  6828
Name: prev_owner, dtype: int64
########################################



In [556]:
# Checking previous_owners column

first_look("previous_owners")

column name :  previous_owners
--------------------------------
Percent_of_Nulls   :  % 41.71
Number_of_Nulls   :  6640
Number_of_Uniques :  101
Value_counts :
 1                                                                      8103
NaN                                                                    6640
2                                                                       766
0                                                                       163
3                                                                        17
                                                                       ... 
1,111 g CO2/km (comb)                                                     1
1,Euro 6                                                                  1
2,119 g CO2/km (comb)                                                     1
1,,6.6 l/100 km (comb),,8.1 l/100 km (city),,5.7 l/100 km (country)       1
1,142 g CO2/km (comb)                                                     1
Nam

In [557]:
# previous_owners column can be used to fill missing values at other columns such as prew_owner, consumption, ..
# So it will be decided to drop this column after checking other columns.

In [558]:
# extracting number of owners from prev_owner column

df["prev_owner"] = df.prev_owner.str.extract("(\d)").astype(float)

In [559]:
# Checking null values in prev_owner and previous_owners columns

df[["prev_owner","previous_owners"]].isnull().sum()

prev_owner         6828
previous_owners    6640
dtype: int64

There are 6828 and 6640 null values in prev_owner and prev_owner columns respectively.

In [560]:
# Null values will be worked in next notebook.

### hp column

In [561]:
# Checking the hp column

first_look("hp")

column name :  hp
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  81
Value_counts :
 85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
70 kW      888
125 kW     707
51 kW      695
55 kW      569
118 kW     516
92 kW      466
121 kW     392
147 kW     380
77 kW      345
56 kW      286
54 kW      276
103 kW     253
87 kW      232
165 kW     194
88 kW      177
60 kW      160
162 kW      98
- kW        88
74 kW       81
96 kW       72
71 kW       59
101 kW      47
67 kW       40
154 kW      39
122 kW      35
119 kW      30
164 kW      27
135 kW      24
82 kW       22
52 kW       22
78 kW       20
1 kW        20
294 kW      18
146 kW      18
141 kW      16
57 kW       10
104 kW       8
120 kW       8
191 kW       7
112 kW       7
155 kW       6
117 kW       6
184 kW       5
90 kW        4
76 kW        4
65 kW        4
149 kW       3
80 kW        3
168 kW       3
98 kW        3
93 kW        3
228 kW       2
270

In [562]:
# Extracting hp values from hp column and assign them to hp_kw column and fixing data type

df["hp_kw"]= df.hp.str.extract(r"(\d+)").astype(float)

In [563]:
# Dropping hp column

df.drop(columns="hp",inplace=True)

In [564]:
df.shape

(15919, 42)

In [565]:
# Checking null values in hp_kw column after cleaning

df.hp_kw.isnull().sum()

88

There are 88 null values in hp_kw column.

In [566]:
# Null values will be worked in next notebook.

### type column

In [567]:
# Checking the type column

first_look("type")

column name :  type
--------------------------------
Percent_of_Nulls   :  % 0.01
Number_of_Nulls   :  2
Number_of_Uniques :  169
Value_counts :
 Used,,Diesel (Particulate Filter)                                                                                 3475
Used,,Diesel                                                                                                      2516
Used,,Gasoline                                                                                                    2367
Used,,Super 95                                                                                                    1818
Pre-registered,,Super 95                                                                                           500
                                                                                                                  ... 
New,,Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95       1
Used,,Super 95 / Supe

In [568]:
# Checking type and fuel column together

df[["type","fuel"]].head(50)

type                         fuel
0             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
1                                Used,,Gasoline                     Gasoline
2             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
3             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
4             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
5             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
6             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
7             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
8             Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
9                                Used,,Gasoline                     Gasoline
10            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
11                               Used,,Super 95                     Super 95
12                     Used,,Regular/Benzine 91           Regular/Benzine 91
13                               Used,,Gasoline                     Gasoline
14                               Used,,Super 95                     Super 95
15  Employee's car,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
16                                 Used,,Diesel                       Diesel
17            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
18                               Used,,Gasoline                     Gasoline
19            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
20            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
21                               Used,,Super 95                     Super 95
22                               Used,,Gasoline                     Gasoline
23            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
24                               Used,,Gasoline                     Gasoline
25                               Used,,Gasoline                     Gasoline
26                               Used,,Super 95                     Super 95
27                               Used,,Gasoline                     Gasoline
28                                 Used,,Diesel                       Diesel
29                               Used,,Super 95                     Super 95
30                                 Used,,Diesel                       Diesel
31            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
32                               Used,,Super 95                     Super 95
33            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
34                                 Used,,Diesel                       Diesel
35                               Used,,Super 95                     Super 95
36                     Used,,Regular/Benzine 91           Regular/Benzine 91
37                                 Used,,Diesel                       Diesel
38                               Used,,Gasoline                     Gasoline
39            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
40                               Used,,Super 95                     Super 95
41            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
42            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
43            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
44            Used,,Diesel (Particulate Filter)  Diesel (Particulate Filter)
45                               Used,,Super 95                     Super 95
46                                 Used,,Diesel                       Diesel
47                                 Used,,Diesel                       Diesel
48                               Used,,Super 95                     Super 95
49                     Used,,Regular/Benzine 91           Regular/Benzine 91

In [569]:
# Extracting necessary values from type column : 1st method

df["type"] = df.type.str.extract(r"(.+),,")
df.type.value_counts()

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: type, dtype: int64

In [570]:
# Extracting necessary values from type column : 2nd method

# df.type.str.split(",").str[1].value_counts()

In [571]:
# Checking null values after cleaning

df.type.isnull().sum()

2

There are only 2 null values in type column.

In [572]:
# Null values will be worked in next notebook.

### next_inspection column

In [573]:
# Checking the next_inspection column

first_look("next_inspection")

column name :  next_inspection
--------------------------------
Percent_of_Nulls   :  % 77.79
Number_of_Nulls   :  12384
Number_of_Uniques :  1384
Value_counts :
 NaN                            12384
04/2022                           62
06/2021                           47
03/2021                           39
03/2022                           36
                               ...  
06/2021,121 g CO2/km (comb)        1
02/2020,139 g CO2/km (comb)        1
10/2021,136 g CO2/km (comb)        1
06/2019,139 g CO2/km (comb)        1
01/2022,168 g CO2/km (comb)        1
Name: next_inspection, Length: 1385, dtype: int64

Value_counts with sort index :
 01/1921,120 g CO2/km (comb)        1
01/1955                            1
01/1999                            1
01/2001,120 g CO2/km (comb)        1
01/2001,122 g CO2/km (comb)        2
                               ...  
12/2021,153 g CO2/km (comb)        4
12/2021,167 g CO2/km (comb)        1
12/2021,Euro 6                     1
12/2022       

In [574]:
# Checking next_inspection and inspection_new columns together

df[["next_inspection","inspection_new"]].head(50)

next_inspection           inspection_new
0    06/2021,99 g CO2/km (comb)               Yes,Euro 6
1                           NaN                      NaN
2                           NaN                      NaN
3                           NaN                      NaN
4                           NaN  Yes,109 g CO2/km (comb)
5                           NaN                      NaN
6                           NaN   Yes,98 g CO2/km (comb)
7                           NaN   Yes,97 g CO2/km (comb)
8    02/2020,97 g CO2/km (comb)                      NaN
9                           NaN                      NaN
10                          NaN                      NaN
11                          NaN  Yes,112 g CO2/km (comb)
12  09/2019,112 g CO2/km (comb)                      NaN
13                          NaN                      NaN
14   10/2019,99 g CO2/km (comb)                      NaN
15   04/2020,97 g CO2/km (comb)                      NaN
16                          NaN                      NaN
17                          NaN                      NaN
18                      07/2020                      NaN
19                          NaN                      NaN
20                          NaN                      NaN
21                          NaN  Yes,0 kWh/100 km (comb)
22  12/2019,112 g CO2/km (comb)                      NaN
23                          NaN                      NaN
24                          NaN                      NaN
25                          NaN                      NaN
26                          NaN   Yes,97 g CO2/km (comb)
27                          NaN                      NaN
28                          NaN                      NaN
29                          NaN                      NaN
30                          NaN                      NaN
31   05/2019,95 g CO2/km (comb)                      NaN
32                          NaN  Yes,104 g CO2/km (comb)
33                          NaN                      NaN
34                          NaN                      NaN
35                          NaN  Yes,104 g CO2/km (comb)
36                          NaN  Yes,104 g CO2/km (comb)
37   07/2019,97 g CO2/km (comb)                      NaN
38   10/2019,97 g CO2/km (comb)                      NaN
39                          NaN                      NaN
40                          NaN  Yes,102 g CO2/km (comb)
41                          NaN   Yes,91 g CO2/km (comb)
42                          NaN   Yes,91 g CO2/km (comb)
43                          NaN                      NaN
44   02/2021,94 g CO2/km (comb)                      NaN
45   06/2019,99 g CO2/km (comb)                      NaN
46                          NaN                      NaN
47                          NaN                      NaN
48                          NaN  Yes,102 g CO2/km (comb)
49                          NaN  Yes,0 kWh/100 km (comb)

There isn't any similarities between next_inspection and inspection_new columns. So these columns will be examined seperately.

In [575]:
# Extracting date information from next_inspection columns and assign them to a new column named next_insp_date

df["next_insp_date"] = df.next_inspection.str.extract(r"(\d+/\d{0,4})")

In [576]:
df["next_insp_date"].isnull().sum()

12384

There are 12384 null values.

next_inspection column can be used to fill missing values in other columns. So it will drop later.

In [577]:
# Null values will be worked in next notebook.

### inspection_new column

In [578]:
# Checking the inspection_new column

first_look("inspection_new")

column name :  inspection_new
--------------------------------
Percent_of_Nulls   :  % 75.3
Number_of_Nulls   :  11987
Number_of_Uniques :  201
Value_counts :
 NaN                                                                      11987
Yes,Euro 6                                                                 523
Yes                                                                        442
Yes,102 g CO2/km (comb)                                                    174
Yes,4 (Green)                                                              166
                                                                         ...  
Yes,,5.2 l/100 km (comb),,6.7 l/100 km (city),,4.2 l/100 km (country)        1
Yes,100 g CO2/km (comb)                                                      1
Yes,,4.9 l/100 km (comb),,5.9 l/100 km (city),,4.3 l/100 km (country)        1
Yes,,5.1 l/100 km (comb),,6.4 l/100 km (city),,4.3 l/100 km (country)        1
Yes,172 g CO2/km (comb)                           

In [579]:
# Extracting necessary information from inspection_new column and assign them into a new column
# named insp_new

df["insp_new"] = df.inspection_new.str.extract(r"(Yes)")

In [580]:
df["insp_new"].isnull().sum()

11987

There are 11987 null values.

inspection_new column can be used to fill missing values in other columns. So it will drop later.

In [581]:
# Null values will be worked in next notebook.

### warranty column

In [582]:
# Checking the warranty column

first_look("warranty")

column name :  warranty
--------------------------------
Percent_of_Nulls   :  % 42.48
Number_of_Nulls   :  6763
Number_of_Uniques :  505
Value_counts :
 NaN                                                                          6763
Euro 6                                                                       1868
12 months                                                                    1305
24 months                                                                     585
4 (Green)                                                                     517
                                                                             ... 
2 months                                                                        1
72 months,125 g CO2/km (comb)                                                   1
60 months,14 g CO2/km (comb)                                                    1
24 months,121 g CO2/km (comb)                                                   1
36 months,,7.4 l/100 km (c

In [583]:
# Extracting necessary values from warranty column and assign them into a new column named warranty_month
# fixing data type

df["warranty_month"] = df.warranty.str.extract(r"(\d+)\s*month").astype(float)

In [584]:
df["warranty_month"].isnull().sum()

11066

warranty column can be used to fill other columns. Then can be dropped.

There are 11066 null values.

In [585]:
# Null values will be worked in next notebook.

### full_service column

In [586]:
# Checking the full_service column

first_look("full_service")

column name :  full_service
--------------------------------
Percent_of_Nulls   :  % 60.86
Number_of_Nulls   :  9689
Number_of_Uniques :  120
Value_counts :
 NaN                                                                 9689
4 (Green)                                                           2235
Euro 6                                                              2097
Euro 6d-TEMP                                                         399
120 g CO2/km (comb)                                                  105
                                                                    ... 
6 l/100 km (comb),,8 l/100 km (city),,4.9 l/100 km (country)           1
84 g CO2/km (comb)                                                     1
87 g CO2/km (comb)                                                     1
5.7 l/100 km (comb),,7.3 l/100 km (city),,4.9 l/100 km (country)       1
Euro 4                                                                 1
Name: full_service, Length: 121, dtype:

In [587]:
# full_service column can be used to fill other columns' missing values. So it will drop later.

In [588]:
df[df.full_service.notna()][["full_service","co_2_emission","emission_class", "emission_label"]].sample(50)

full_service        co_2_emission emission_class  emission_label
4791             4 (Green)  114 g CO2/km (comb)         Euro 6             NaN
3556             4 (Green)  106 g CO2/km (comb)         Euro 6             NaN
13123            4 (Green)  126 g CO2/km (comb)         Euro 6             NaN
1849             4 (Green)   97 g CO2/km (comb)         Euro 6             NaN
10065            4 (Green)  143 g CO2/km (comb)   Euro 6d-TEMP             NaN
11411               Euro 6  150 g CO2/km (comb)         Euro 6             NaN
11424            4 (Green)  134 g CO2/km (comb)         Euro 6             NaN
7685   154 g CO2/km (comb)  154 g CO2/km (comb)   Euro 6d-TEMP       4 (Green)
4307   106 g CO2/km (comb)  106 g CO2/km (comb)         Euro 6             NaN
10101            4 (Green)  140 g CO2/km (comb)         Euro 6             NaN
1712                Euro 6   89 g CO2/km (comb)         Euro 6             NaN
3543    99 g CO2/km (comb)   99 g CO2/km (comb)         Euro 6             NaN
302     92 g CO2/km (comb)   92 g CO2/km (comb)         Euro 6       4 (Green)
8561                Euro 6                  NaN         Euro 6             NaN
10809  129 g CO2/km (comb)  129 g CO2/km (comb)         Euro 6             NaN
9156                Euro 6  120 g CO2/km (comb)         Euro 6             NaN
3365   103 g CO2/km (comb)  103 g CO2/km (comb)         Euro 6             NaN
10967               Euro 6  109 g CO2/km (comb)         Euro 6             NaN
1693             4 (Green)  109 g CO2/km (comb)         Euro 6             NaN
15337               Euro 6  120 g CO2/km (comb)         Euro 6             NaN
5084   117 g CO2/km (comb)  117 g CO2/km (comb)         Euro 6       4 (Green)
11856            4 (Green)  141 g CO2/km (comb)         Euro 6             NaN
4695   112 g CO2/km (comb)  112 g CO2/km (comb)         Euro 6             NaN
4793             4 (Green)  108 g CO2/km (comb)         Euro 6             NaN
1534             4 (Green)  102 g CO2/km (comb)         Euro 6             NaN
4801                Euro 6  104 g CO2/km (comb)         Euro 6             NaN
11125             5 (Blue)  104 g CO2/km (comb)         Euro 6             NaN
3074             4 (Green)  109 g CO2/km (comb)         Euro 6             NaN
12923         Euro 6d-TEMP  139 g CO2/km (comb)            NaN             NaN
14338            4 (Green)  127 g CO2/km (comb)         Euro 6             NaN
2510   104 g CO2/km (comb)  104 g CO2/km (comb)   Euro 6d-TEMP       4 (Green)
8005                Euro 6                  NaN         Euro 6             NaN
6731                Euro 6   92 g CO2/km (comb)         Euro 6             NaN
7895                Euro 6                  NaN         Euro 6             NaN
11690               Euro 6  141 g CO2/km (comb)         Euro 6             NaN
10571               Euro 6  189 g CO2/km (comb)         Euro 6             NaN
9212             4 (Green)  123 g CO2/km (comb)         Euro 6             NaN
7146             4 (Green)  128 g CO2/km (comb)         Euro 6             NaN
7354                Euro 6  127 g CO2/km (comb)         Euro 6             NaN
1729             4 (Green)   99 g CO2/km (comb)         Euro 6             NaN
5772                Euro 6  124 g CO2/km (comb)            NaN       4 (Green)
15442  140 g CO2/km (comb)  140 g CO2/km (comb)         Euro 6             NaN
1239   120 g CO2/km (comb)  120 g CO2/km (comb)         Euro 6       4 (Green)
13606   85 g CO2/km (comb)   85 g CO2/km (comb)         Euro 6             NaN
2729   113 g CO2/km (comb)  113 g CO2/km (comb)         Euro 6             NaN
8510   137 g CO2/km (comb)  137 g CO2/km (comb)            NaN  1 (No sticker)
1241   120 g CO2/km (comb)  120 g CO2/km (comb)         Euro 6       4 (Green)
636                 Euro 6                  NaN         Euro 6             NaN
9756   120 g CO2/km (comb)  120 g CO2/km (comb)         Euro 6             NaN
14821              Euro 6c  127 g CO2/km (comb)        Euro 6c  

### non_smoking_vehicle column

In [589]:
# Checking the non_smoking_vehicle column

first_look("non_smoking_vehicle")

column name :  non_smoking_vehicle
--------------------------------
Percent_of_Nulls   :  % 78.26
Number_of_Nulls   :  12459
Number_of_Uniques :  92
Value_counts :
 NaN                                                                 12459
4 (Green)                                                            1240
Euro 6                                                               1127
Euro 6d-TEMP                                                          345
120 g CO2/km (comb)                                                    63
85 g CO2/km (comb)                                                     46
107 g CO2/km (comb)                                                    36
104 g CO2/km (comb)                                                    36
153 g CO2/km (comb)                                                    31
124 g CO2/km (comb)                                                    29
1 (No sticker)                                                         24
99 g CO2/km (comb)   

Diƒüer kolonlarƒ±n doldurulmasƒ±nda kullanƒ±labilir. Sonrasƒ±nda d√º≈ü√ºlecek.

### offer_number column

In [590]:
# Checking the offer_number column

first_look("offer_number")

column name :  offer_number
--------------------------------
Percent_of_Nulls   :  % 19.94
Number_of_Nulls   :  3175
Number_of_Uniques :  11440
Value_counts :
 NaN                                         3175
LT67679                                       27
UN89904                                       27
XJ38068                                       27
JV03654                                       27
                                            ... 
160_dcbb6c3e-a6da-43a3-8754-ccd994cec93b       1
6701576                                        1
6701569                                        1
158121                                         1
Re_30000008029                                 1
Name: offer_number, Length: 11441, dtype: int64

Value_counts with sort index :
 # 250678          1
# 8H6050830       1
# G1024529        1
# G6050580        1
#8023778          2
               ... 
x_45689v          2
y8fx64x           1
zr11914           1
zr11916           1
NaN            3175


In [591]:
df.offer_number.sample(50)

6214                   6307JNR
13262         re77c1-ET-772-QG
5602                     56901
6246                     G-214
11097                      NaN
727                     020533
6558                   LT67679
2002                    63175X
10166                    11153
10210                   362173
1237                   TP62881
4502                   A122641
4938                    099338
10012                  4144104
1108                   U_18034
12651                    22735
15813                  2223117
2126                   4980985
5018                     26607
3738                       NaN
15112                 rv335533
11504                      NaN
3477                       NaN
9502                       NaN
7231                   AS1598C
13072                GW-STR094
10357                   420283
10714                   XN567K
4085                   4712247
6948                       853
4005                AZ59-34117
3895     garanzia_48_mesi_apsp
7731    

In [592]:
# As offer_number column doesn't have any usefull/related data with car price,
# it was decided to drop this column.

df.drop(columns="offer_number",inplace=True)

In [593]:
df.shape

(15919, 44)

### body_color

In [594]:
# Checking the body_color column

first_look("body_color")

column name :  body_color
--------------------------------
Percent_of_Nulls   :  % 3.75
Number_of_Nulls   :  597
Number_of_Uniques :  14
Value_counts :
 Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: body_color, dtype: int64

Value_counts with sort index :
 Beige      108
Black     3745
Blue      1431
Bronze       6
Brown      289
Gold         2
Green      154
Grey      3505
Orange       3
Red        957
Silver    1647
Violet      18
White     3406
Yellow      51
NaN        597
Name: body_color, dtype: int64
########################################



In [595]:
# Null values will be worked in next notebook.

### paint_type column

In [596]:
# Checking the paint_type column

first_look("paint_type")

column name :  paint_type
--------------------------------
Percent_of_Nulls   :  % 36.26
Number_of_Nulls   :  5772
Number_of_Uniques :  3
Value_counts :
 Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

Value_counts with sort index :
 Metallic       9794
Perl effect       6
Uni/basic       347
NaN            5772
Name: paint_type, dtype: int64
########################################



In [597]:
# Null values will be worked in next notebook.

### body_color_original column

In [598]:
# Checking the body_color_original column

first_look("body_color_original")

column name :  body_color_original
--------------------------------
Percent_of_Nulls   :  % 23.61
Number_of_Nulls   :  3759
Number_of_Uniques :  1927
Value_counts :
 NaN                              3759
Onyx Schwarz                      338
Bianco                            282
Mythosschwarz Metallic            238
Brillantschwarz                   216
                                 ... 
Rouge-Braun (G0Y)                   1
VARI COLRI DISPONIBILI              1
Kokosnussbraun Metallic             1
Farbe frei w√§hlbar                  1
Perlmutt-Wei√ü Metallic (Wei√ü)       1
Name: body_color_original, Length: 1928, dtype: int64

Value_counts with sort index :
 "PLATIN"                          1
"satinsilber "                    1
(0C0C) Monsungrau Metallic        1
(B4B4) Cortinaweiss               1
(NNP)                             1
                               ... 
w√§hlbar - ggf. mit Aufpreis     118
w√§hlbar -ggfl. mit Aufpreis       1
w√§hlbar, ggf gegen Aufpreis       2

In [599]:
df[["body_color", "paint_type","body_color_original"]].sample(50)

body_color paint_type             body_color_original
4252        Grey   Metallic                            GRIS
1187       White        NaN             (B4B4) Cortinaweiss
11568      White   Metallic                    Schnee Weiss
12902        NaN        NaN                             NaN
3155       White        NaN                          Blanco
3387       Black        NaN                             NaN
12466      White   Metallic  SchneeWeiss/SummitWhite/Arctic
5248        Grey   Metallic                    Grigio scuro
6188        Grey   Metallic             Karbongrau metallic
2641       White        NaN                             NaN
8141       Black   Metallic               Onyx Schwarz (M2)
1613      Silver   Metallic                   florettsilber
5021       White        NaN                        Ibiswei√ü
12228     Silver   Metallic                          silber
11982       Grey   Metallic                            grau
2291       Black   Metallic          Mythosschwarz Metallic
15248      White        NaN                          Blanco
10735      Black   Metallic           karbonschwarz graphit
1772      Silver   Metallic                             NaN
12086       Grey   Metallic                          Grigio
15875      Black   Metallic                     black pearl
1339         Red   Metallic            Misanorot Perleffekt
5372       Black        NaN       Brilliant Schwarz/Schwarz
8343        Grey   Metallic               Son of a Gun Grey
5973      Silver   Metallic       SWITCHBLADE SILVER MET (G
1291       Black   Metallic                   Mythosschwarz
10         Black   Metallic                            Nero
15456      Black        NaN                     Noir Etoil√©
2804        Grey   Metallic                            Gris
12369       Grey   Metallic                       QuarzGrau
10407      White   Metallic               schnee wei√ü (uni)
8052       Black   Metallic                    Onyx Schwarz
1967         Red  Uni/basic                           Rosso
11258       Grey   Metallic                      Quarz Grau
12736      Brown        NaN                     Rouge Braun
10872       Blue   Metallic                             NaN
4485       Black        NaN            brillantschwarz Klar
14068      Black   Metallic    Black Pearl-Schwarz Metallic
6360        Grey   Metallic           QUARZ GRAU PERLEFFEKT
1020       Brown   Metallic       Soho Brown (bruin metalli
10825     Silver        NaN                             NaN
13684        NaN        NaN                    TEINTE CAISS
1427         Red   Metallic                      Rood/Rouge
2182       White        NaN                     Cortinawei√ü
15286       Grey        NaN                   Gris Casiopea
7179       Black   Metallic                     Onyxschwarz
8410       Black   Metallic                     Onyxschwarz
1063       White        NaN                   BLANC GLACIER
2946         Red   Metallic                           Rosso
12195       Grey        NaN                            Gris

In [600]:
# The number of null values in body_color column

df.body_color.isnull().sum()

597

In [601]:
# Checking how many of the null values in body_color column are not null in body_color_original column

df[df.body_color.isnull()]["body_color_original"].notna().sum()

407

As a result of the analysis of above, it was decided that the null values in body_color
can be filled with the corresponding values in body_color_original column.

### upholstery column

In [602]:
#Checking the upholstery column

first_look("upholstery")

column name :  upholstery
--------------------------------
Percent_of_Nulls   :  % 23.37
Number_of_Nulls   :  3720
Number_of_Uniques :  46
Value_counts :
 Cloth, Black           5821
NaN                    3720
Part leather, Black    1121
Cloth                  1005
Cloth, Grey             891
Cloth, Other            639
Full leather, Black     575
Black                   491
Grey                    273
Other, Other            182
Part leather            140
Full leather            139
Full leather, Brown     116
Part leather, Grey      116
Other, Black            110
Full leather, Other      72
Full leather, Grey       67
Part leather, Other      65
Other                    56
Part leather, Brown      50
alcantara, Black         47
Velour, Black            36
Full leather, Beige      36
Cloth, Brown             28
Velour                   16
Other, Grey              15
Cloth, Beige             13
Brown                    12
Cloth, Blue              12
Velour, Grey              8
Cloth

In [603]:
# splitting upholstery column into upholstery_type and upholstery_color seperate columns

df.upholstery.str.extract(r"(.+)[.+](.+)?")[1].value_counts(dropna=False)

NaN    15919
Name: 1, dtype: int64

In [604]:
df.upholstery.str.extract(r"(.+),(.+)")

0       1
0             Cloth   Black
1             Cloth    Grey
2             Cloth   Black
3               NaN     NaN
4             Cloth   Black
...             ...     ...
15914           NaN     NaN
15915           NaN     NaN
15916  Full leather   Black
15917           NaN     NaN
15918  Full leather   Brown

[15919 rows x 2 columns]

In [605]:
# creating upholstery type list from upholstery column values using extract, dropna and unique methods.

type_list = list(df.upholstery.str.extract(r"(.+),(.+)")[0].dropna().unique())
type_list

['Cloth', 'Part leather', 'Full leather', 'Other', 'alcantara', 'Velour']

In [606]:
# creating upholstery color list from upholstery column values using extract, dropna and unique methods.

color_list = list(df.upholstery.str.extract(r"(.+),\s*(.+)")[1].dropna().unique())
color_list

['Black',
 'Grey',
 'Other',
 'White',
 'Red',
 'Blue',
 'Orange',
 'Brown',
 'Beige',
 'Yellow']

In [607]:
# splitting upholstery column values into two column

df[["upholstery_type","upholstery_color"]] = df.upholstery.str.split(", ", expand=True)

In [608]:
# As it is seen below output there are some color values in type column. So they need to be fixed.

df["upholstery_type"].value_counts(dropna=False)

Cloth           8423
NaN             3720
Part leather    1499
Full leather    1009
Black            491
Other            368
Grey             273
Velour            60
alcantara         57
Brown             12
Beige              3
Blue               2
White              2
Name: upholstery_type, dtype: int64

In [609]:
# Checking upholstery_color values whether there is upholstery_type value in it.

df["upholstery_color"].value_counts(dropna=False)

Black     7710
NaN       5861
Grey      1103
Other      960
Brown      195
Beige       51
Blue        14
White       11
Red          9
Yellow       4
Orange       1
Name: upholstery_color, dtype: int64

In [610]:
# Determining color values in the upholstery_type column

df.upholstery_type[df.upholstery_type.isin(color_list)]

29       Black
55       Other
64       Black
95       Other
112      Black
         ...  
15783    Other
15821    Other
15866    Brown
15896     Grey
15902    Brown
Name: upholstery_type, Length: 1151, dtype: object

In [611]:
# Assigning the color values which are in upholstery_type column to upholstery_color column

df.upholstery_color.fillna(df.upholstery_type[df.upholstery_type.isin(color_list)], inplace=True)

In [612]:
# Checking the values in upholstery_color column

df["upholstery_color"].value_counts(dropna=False)

Black     8201
NaN       5022
Grey      1376
Other     1016
Brown      207
Beige       54
Blue        16
White       13
Red          9
Yellow       4
Orange       1
Name: upholstery_color, dtype: int64

In [613]:
# Replacing color values which are in upholstery_type column with null. 

df.upholstery_type[df.upholstery_type.isin(color_list)] = np.nan

In [614]:
# Checking the values in upholstery_type column

df.upholstery_type.value_counts(dropna=False)

Cloth           8423
NaN             4871
Part leather    1499
Full leather    1009
Velour            60
alcantara         57
Name: upholstery_type, dtype: int64

In [615]:
df[["upholstery_type","upholstery_color"]].notna().sum()

upholstery_type     11048
upholstery_color    10897
dtype: int64

In [616]:
df[["upholstery_type","upholstery_color"]].isnull().sum()

upholstery_type     4871
upholstery_color    5022
dtype: int64

In [617]:
df[["upholstery", "upholstery_type","upholstery_color"]].sample(50)

upholstery upholstery_type upholstery_color
2152                   NaN             NaN              NaN
6813          Cloth, Black           Cloth            Black
2454                   NaN             NaN              NaN
1954                   NaN             NaN              NaN
6925          Cloth, Black           Cloth            Black
1412           Cloth, Grey           Cloth             Grey
15585  Part leather, Black    Part leather            Black
8890          Cloth, Black           Cloth            Black
10276         Cloth, Black           Cloth            Black
1720         Velour, Black          Velour            Black
247           Other, Other             NaN            Other
11239         Cloth, Black           Cloth            Black
1377          Cloth, Black           Cloth            Black
11536                  NaN             NaN              NaN
10706         Cloth, Black           Cloth            Black
8635                   NaN             NaN              NaN
190                    NaN             NaN              NaN
15806  Full leather, Brown    Full leather            Brown
11690         Cloth, Black           Cloth            Black
12281                  NaN             NaN              NaN
644                    NaN             NaN              NaN
13389                  NaN             NaN              NaN
14985         Part leather    Part leather              NaN
3831                   NaN             NaN              NaN
1196                   NaN             NaN              NaN
4185          Cloth, Black           Cloth            Black
9000          Cloth, Other           Cloth            Other
7632   Full leather, Black    Full leather            Black
14542         Cloth, Black           Cloth            Black
3949          Cloth, Black           Cloth            Black
4408          Cloth, Other           Cloth            Other
2133                   NaN             NaN              NaN
11213                  NaN             NaN              NaN
10110         Cloth, Other           Cloth            Other
15818  Full leather, Brown    Full leather            Brown
1392                   NaN             NaN              NaN
9918          Cloth, Black           Cloth            Black
5310          Cloth, Other           Cloth            Other
5304          Cloth, Black           Cloth            Black
12114  Part leather, Black    Part leather            Black
7470          Cloth, Black           Cloth            Black
4770                   NaN             NaN              NaN
12697         Cloth, Other           Cloth            Other
3354                   NaN             NaN              NaN
11904  Part leather, Black    Part leather            Black
5353          Cloth, Black           Cloth            Black
10364          Cloth, Grey           Cloth             Grey
9553          Cloth, Black           Cloth            Black
6004                   NaN             NaN              NaN
1704          Cloth, Black           Cloth            Black

In [618]:
# dropping upholstery column

df.drop(columns="upholstery", inplace=True)

### nr_of_doors column

In [619]:
# Checking the nr_of_doors column

first_look("nr_of_doors")

column name :  nr_of_doors
--------------------------------
Percent_of_Nulls   :  % 1.33
Number_of_Nulls   :  212
Number_of_Uniques :  6
Value_counts :
 5      11575
4       3079
3        832
2        219
NaN      212
1          1
7          1
Name: nr_of_doors, dtype: int64

Value_counts with sort index :
 1          1
2        219
3        832
4       3079
5      11575
7          1
NaN      212
Name: nr_of_doors, dtype: int64
########################################



In [620]:
# fixing data type

df["nr_of_doors"]= df.nr_of_doors.astype(float)

In [621]:
# Null values will be worked in next notebook.

### nr_of_seats column

In [622]:
# Checking the nr_of_seats column

first_look("nr_of_seats")

column name :  nr_of_seats
--------------------------------
Percent_of_Nulls   :  % 6.14
Number_of_Nulls   :  977
Number_of_Uniques :  6
Value_counts :
 5      13336
4       1125
NaN      977
7        362
2        116
6          2
3          1
Name: nr_of_seats, dtype: int64

Value_counts with sort index :
 2        116
3          1
4       1125
5      13336
6          2
7        362
NaN      977
Name: nr_of_seats, dtype: int64
########################################



In [623]:
# fixing data type

df["nr_of_seats"]= df.nr_of_seats.astype(float)

In [624]:
# Null values will be worked in next notebook.

### model_code column

In [625]:
# Checking the model_code column

first_look("model_code")

column name :  model_code
--------------------------------
Percent_of_Nulls   :  % 68.73
Number_of_Nulls   :  10941
Number_of_Uniques :  232
Value_counts :
 NaN         10941
0035/BCB      268
0588/BNO      245
0588/BDB      206
0588/BHX      188
            ...  
0035/AVN        1
0035/BEM        1
0035/BAG        1
0035/BAA        1
3333/BKG        1
Name: model_code, Length: 233, dtype: int64

Value_counts with sort index :
 0000/000       21
0000/035        1
0000/ACP        1
0035/AAA        1
0035/AAD        1
            ...  
3333/BJR       79
3333/BKG        1
3333/BKQ       18
3333/BKR        8
NaN         10941
Name: model_code, Length: 233, dtype: int64
########################################



In [626]:
# As there isn't any usefull/related information about car price,
# it was decided to drop model_code column.

df.drop(columns="model_code", inplace=True)

In [627]:
df.shape

(15919, 44)

### gearing_type column

In [628]:
# Checking the gearing_type column

first_look("gearing_type")

column name :  gearing_type
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  3
Value_counts :
 Manual            8153
Automatic         7297
Semi-automatic     469
Name: gearing_type, dtype: int64

Value_counts with sort index :
 Automatic         7297
Manual            8153
Semi-automatic     469
Name: gearing_type, dtype: int64
########################################



This column is already clean.

### displacement column

In [629]:
# Checking the displacement column

first_look("displacement")

column name :  displacement
--------------------------------
Percent_of_Nulls   :  % 3.12
Number_of_Nulls   :  496
Number_of_Uniques :  77
Value_counts :
 1,598 cc     4761
999 cc       2438
1,398 cc     1314
1,399 cc      749
1,229 cc      677
1,956 cc      670
1,461 cc      595
1,490 cc      559
NaN           496
1,422 cc      467
1,197 cc      353
898 cc        351
1,395 cc      320
1,968 cc      301
1,149 cc      288
1,618 cc      212
1,798 cc      210
1,498 cc      196
1,600 cc      130
1,248 cc      110
1,997 cc      103
1,364 cc      102
1,400 cc       90
998 cc         72
1,500 cc       50
2,000 cc       46
1,000 cc       40
1 cc           36
1,998 cc       25
2,480 cc       20
1,200 cc       18
1,984 cc       18
1,397 cc       11
899 cc         11
160 cc          6
929 cc          5
1,499 cc        5
997 cc          4
1,596 cc        4
139 cc          4
900 cc          4
1,599 cc        3
1,199 cc        3
1,396 cc        3
1,495 cc        2
1,589 cc        2
1,300 cc        2

In [630]:
# Replacing "," character with "" and extracting digits from displacement column.

df["displacement"] = df.displacement.str.replace(",", "").str.extract(r"(\d+)").astype(float)

In [631]:
# Renaming the displacement column as displacement_cc

df.rename(columns={"displacement":"displacement_cc"}, inplace=True)

In [632]:
df.displacement_cc.isnull().sum()

496

In [633]:
# Null values will be worked in next notebook.

### cylinders columns

In [634]:
# Checking the cylinders column

first_look("cylinders")

column name :  cylinders
--------------------------------
Percent_of_Nulls   :  % 35.68
Number_of_Nulls   :  5680
Number_of_Uniques :  7
Value_counts :
 4      8105
NaN    5680
3      2104
5        22
6         3
8         2
2         2
1         1
Name: cylinders, dtype: int64

Value_counts with sort index :
 1         1
2         2
3      2104
4      8105
5        22
6         3
8         2
NaN    5680
Name: cylinders, dtype: int64
########################################



In [635]:
# fixing data type

df["cylinders"] = df.cylinders.astype(float)

In [636]:
# Null values will be worked in next notebook.

### weight column

In [637]:
# Checking the weight column

first_look("weight")

column name :  weight
--------------------------------
Percent_of_Nulls   :  % 43.81
Number_of_Nulls   :  6974
Number_of_Uniques :  434
Value_counts :
 NaN         6974
1,163 kg     574
1,360 kg     356
1,165 kg     301
1,335 kg     242
            ... 
1,960 kg       1
1,258 kg       1
1,167 kg       1
1,331 kg       1
2,037 kg       1
Name: weight, Length: 435, dtype: int64

Value_counts with sort index :
 1 kg           2
1,009 kg       1
1,010 kg       3
1,017 kg       1
1,030 kg       1
            ... 
840 kg         1
900 kg         1
977 kg         2
980 kg        11
NaN         6974
Name: weight, Length: 435, dtype: int64
########################################



In [638]:
# Replacing "," character with "", extracting digits from weight column
# and assign as weight_kg column.

df["weight_kg"] = df.weight.str.replace(",", "").str.extract(r"(\d+)").astype(float)

In [639]:
# drop weight column

df.drop(columns="weight", inplace=True)

In [640]:
df.shape

(15919, 44)

In [641]:
df.weight_kg.isnull().sum()

6974

In [642]:
# Null values will be worked in next notebook.

### drive_chain column

In [643]:
# Checking the drive_chain column

first_look("drive_chain")

column name :  drive_chain
--------------------------------
Percent_of_Nulls   :  % 43.08
Number_of_Nulls   :  6858
Number_of_Uniques :  3
Value_counts :
 front    8886
NaN      6858
4WD       171
rear        4
Name: drive_chain, dtype: int64

Value_counts with sort index :
 4WD       171
front    8886
rear        4
NaN      6858
Name: drive_chain, dtype: int64
########################################



This column is already clean.

In [644]:
# Null values will be worked in next notebook.

### fuel column

In [645]:
# Checking the fuel column

first_look("fuel")

column name :  fuel
--------------------------------
Percent_of_Nulls   :  % 0.0
Number_of_Nulls   :  0
Number_of_Uniques :  77
Value_counts :
 Diesel (Particulate Filter)                                                                                                       4315
Super 95                                                                                                                          3338
Gasoline                                                                                                                          3175
Diesel                                                                                                                            2984
Super 95 / Regular/Benzine 91                                                                                                      424
Regular/Benzine 91                                                                                                                 354
Super E10 95                                  

In [646]:
# For further analysis it will be better to categorize fuel column.
# Defining lpg, diesel, bensine and electirc/hybrid lists with the related values in fuel column

lpg = ["lpg", "CNG", "Domestic gas H", "Biogas"]
diesel = ["Diesel", "Biodiesel"]
benzine =["Gasoline", "Benzine", "Regular", "Super", "Other"]
electric_hybride = ["Electric"]

In [647]:
# Defining a function to categorize fuel column

def fuelcategory(row) :
    if any(x in row for x in lpg):
        return "LPG/CNG"
    elif any(x in row for x in electric_hybride) :
        return "Electric/Hybride"
    elif any(x in row for x in diesel) :
        if "Particulate Filter" in row :
            return "Diesel (Particulate Filter)"
        else :
            return "Diesel"
    else :
        if "Particulate Filter" in row :
            return "Benzine (Particulate Filter)"
        else :
            return "Benzine"
   

In [648]:
# Application of defined function to fuel column

df["fuel"] = df.fuel.apply(fuelcategory)

In [649]:
# Checking the value counts of fuel column after categorization process

df.fuel.value_counts()

Benzine                         8075
Diesel (Particulate Filter)     4315
Diesel                          2985
Benzine (Particulate Filter)     501
LPG/CNG                           38
Electric/Hybride                   5
Name: fuel, dtype: int64

### consumption column

In [650]:
# Checking the consumption column

first_look("consumption")

column name :  consumption
--------------------------------
Percent_of_Nulls   :  % 11.97
Number_of_Nulls   :  1906
Number_of_Uniques :  881
Value_counts :
 NaN                                                                           1906
['3.9 l/100 km (comb)'],['4.1 l/100 km (city)'],['3.7 l/100 km (country)']     304
['4.2 l/100 km (comb)'],['5 l/100 km (city)'],['3.7 l/100 km (country)']       276
['5.4 l/100 km (comb)'],['6.8 l/100 km (city)'],['4.5 l/100 km (country)']     257
['3.8 l/100 km (comb)'],['4.3 l/100 km (city)'],['3.5 l/100 km (country)']     253
                                                                              ... 
['4.2 l/100 km (comb)'],['5.3 l/100 km (city)'],['3.6 l/100 km (country)']       1
5.1 l/100 km (comb),,6.4 l/100 km (city),,4.3 l/100 km (country)                 1
['4.6 l/100 km (comb)'],['5.4 l/100 km (city)'],['6.7 l/100 km (country)']       1
6.3 l/100 km (comb)                                                              1
7.4 l/100 km 

In [651]:
# Cleaning consumption column and taking fuel consumption values into separate columns
# Changing data types of new columns

df["consumption"]=df["consumption"].str.replace("[\[\]']?","")
df["consumption_comb"] = df.consumption.str.extract(r"(\d*\.\d+|\d+).+\(comb\)").astype(float)
df["consumption_city"] = df.consumption.str.extract(r"[.+]?,(\d*\.\d+|\d+).+\(city\)").astype(float)
df["consumption_country"] = df.consumption.str.extract(r".+,(\d*\.\d+|\d+).+\(country\)").astype(float)

In [652]:
# Comparing new columns' values with consumptions' values

df[["consumption","consumption_comb","consumption_city","consumption_country"]].sample(50)

consumption  consumption_comb  \
2858   3.9 l/100 km (comb),4.4 l/100 km (city),3.6 l/...               3.9   
1793   3.8 l/100 km (comb),4.6 l/100 km (city),3.3 l/...               3.8   
14723  5 l/100 km (comb),6.3 l/100 km (city),4.2 l/10...               5.0   
8638   5.1 l/100 km (comb),6.5 l/100 km (city),4.3 l/...               5.1   
5225   5.5 l/100 km (comb),6.9 l/100 km (city),4.7 l/...               5.5   
12682  5.4 l/100 km (comb),7 l/100 km (city),4.6 l/10...               5.4   
1692   4.7 l/100 km (comb),5.8 l/100 km (city),4.1 l/...               4.7   
3435   3.8 l/100 km (comb),4.3 l/100 km (city),3.5 l/...               3.8   
12022  5.7 l/100 km (comb),7.5 l/100 km (city),4.6 l/...               5.7   
9119         5.4 l/100 km (comb),,4.6 l/100 km (country)               5.4   
15674  5.3 l/100 km (comb),6.2 l/100 km (city),4.7 l/...               5.3   
13324  5.4 l/100 km (comb),6.8 l/100 km (city),4.5 l/...               5.4   
14320                                                NaN               NaN   
5326   3.9 l/100 km (comb),4.2 l/100 km (city),3.7 l/...               3.9   
8447   4.7 l/100 km (comb),5.8 l/100 km (city),4 l/10...               4.7   
12309  5.7 l/100 km (comb),7.3 l/100 km (city),4.8 l/...               5.7   
8222   5.9 l/100 km (comb),,7.8 l/100 km (city),,4.8 ...               5.9   
12826  6.3 l/100 km (comb),8 l/100 km (city),5.3 l/10...               6.3   
11523  5.6 l/100 km (comb),7.8 l/100 km (city),4.3 l/...               5.6   
3297                                                 NaN               NaN   
6519   4 l/100 km (comb),5 l/100 km (city),3 l/100 km...               4.0   
1587                                                 NaN               NaN   
3607   4.5 l/100 km (comb),5.5 l/100 km (city),3.9 l/...               4.5   
11245  5.7 l/100 km (comb),7.3 l/100 km (city),4.8 l/...               5.7   
2296                               4.9 l/100 km (comb),,               4.9   
3305   3.4 kg/100 km (comb),4.3 kg/100 km (city),2.9 ...               3.4   
11810  5.6 l/100 km (comb),7.1 l/100 km (city),4.7 l/...               5.6   
7583   4.5 l/100 km (comb),5.4 l/100 km (city),4 l/10...               4.5   
9825                               5.4 l/100 km (comb),,               5.4   
9380   5.6 l/100 km (comb),7 l/100 km (city),4.8 l/10...               5.6   
12238  6 l/100 km (comb),7.3 l/100 km (city),5.2 l/10...               6.0   
9801   5.2 l/100 km (comb),6.8 l/100 km (city),4.3 l/...               5.2   
8660   5.4 l/100 km (comb),6.7 l/100 km (city),4.6 l/...               5.4   
6199                                                 NaN               NaN   
9287                                                 NaN               NaN   
7024   3.7 l/100 km (comb),4.2 l/100 km (city),3.3 l/...               3.7   
9243   5.4 l/100 km (comb),6.7 l/100 km (city),4.6 l/...               5.4   
10490  3.9 l/100 km (comb),4.6 l/100 km (city),3.6 l/...               3.9   
6694   4.5 l/100 km (comb),5.6 l/100 km (city),3.9 l/...               4.5   
7078   5.6 l/100 km (comb),7.3 l/100 km (city),4.6 l/...               5.6   
1673   4.4 l/100 km (comb),5.4 l/100 km (city),3.8 l/...               4.4   
11206  3.9 l/100 km (comb),4.6 l/100 km (city),3.6 l/...               3.9   
1445                                                 NaN               NaN   
7533   4.3 l/100 km (comb),5.1 l/100 km (city),3.8 l/...               4.3   
3874   3.9 l/100 km (comb),4.1 l/100 km (city),3.7 l/...               3.9   
4816   4 l/100 km (comb),4.5 l/100 km (city),3.7 l/10...               4.0   
11355  5.2 l/100 km (comb),6.8 l/100 km (city),4.2 l/...               5.2   
4356   3.8 l/100 km (comb),4.5 l/100 km (city),3.4 l/...               3.8   
12570  5.5 l/100 km (comb),7.3 l/100 km (city),4.5 l/...               5.5   
12461  6.3 l/100 km (comb),8 l/100 km (city),5.3 l/10...               6.3   

       consumption_city  consumption_country  
2858               

In [653]:
# Checking the number of null values in new columns

df[["consumption_comb","consumption_city","consumption_country"]].isnull().sum()

consumption_comb       2033
consumption_city       2436
consumption_country    2376
dtype: int64

In [654]:
# Checking the number of non-null values in new columns

df[["consumption_comb","consumption_city","consumption_country"]].notna().sum()

consumption_comb       13886
consumption_city       13483
consumption_country    13543
dtype: int64

In [655]:
# dropping consumption column

df.drop(columns="consumption", inplace=True)

### co_2_emission column

In [656]:
# Checking the co_2_emission column

first_look("co_2_emission")

column name :  co_2_emission
--------------------------------
Percent_of_Nulls   :  % 15.3
Number_of_Nulls   :  2436
Number_of_Uniques :  122
Value_counts :
 NaN                      2436
120 g CO2/km (comb)       740
99 g CO2/km (comb)        545
97 g CO2/km (comb)        537
104 g CO2/km (comb)       501
                         ... 
14 g CO2/km (comb)          1
1,060 g CO2/km (comb)       1
51 g CO2/km (comb)          1
165 g CO2/km (comb)         1
193 g CO2/km (comb)         1
Name: co_2_emission, Length: 123, dtype: int64

Value_counts with sort index :
 0 g CO2/km (comb)           2
1 g CO2/km (comb)           1
1,060 g CO2/km (comb)       1
100 g CO2/km (comb)        36
101 g CO2/km (comb)       105
                         ... 
97 g CO2/km (comb)        537
98 g CO2/km (comb)        151
99 g CO2/km (comb)        545
990 g CO2/km (comb)         1
NaN                      2436
Name: co_2_emission, Length: 123, dtype: int64
########################################



In [657]:
# Replacing "," character with "", extracting digits from co_2_emission column.

df["co_2_emission"] = df.co_2_emission.str.replace(",", "").str.extract(r"(\d+)").astype(float)

In [658]:
df.co_2_emission.isnull().sum()

2436

In [659]:
df.co_2_emission

0         99.0
1        129.0
2         99.0
3         99.0
4        109.0
         ...  
15914    139.0
15915    168.0
15916    139.0
15917    139.0
15918    153.0
Name: co_2_emission, Length: 15919, dtype: float64

In [660]:
df.co_2_emission.value_counts()

120.0      740
99.0       545
97.0       537
104.0      501
102.0      477
          ... 
80.0         1
51.0         1
165.0        1
12324.0      1
193.0        1
Name: co_2_emission, Length: 122, dtype: int64

In [661]:
# Null values will be worked in next notebook.

### emission_class column

In [662]:
# Checking the emission_class column

first_look("emission_class")

column name :  emission_class
--------------------------------
Percent_of_Nulls   :  % 22.79
Number_of_Nulls   :  3628
Number_of_Uniques :  6
Value_counts :
 Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: emission_class, dtype: int64

Value_counts with sort index :
 Euro 4             40
Euro 5             78
Euro 6          10139
Euro 6c           127
Euro 6d            62
Euro 6d-TEMP     1845
NaN              3628
Name: emission_class, dtype: int64
########################################



In [663]:
# Null values will be worked in next notebook.

### comfort_&_convenience column

In [664]:
# Checking the comfort_&_convenience column

first_look("comfort_&_convenience")

column name :  comfort_&_convenience
--------------------------------
Percent_of_Nulls   :  % 5.78
Number_of_Nulls   :  920
Number_of_Uniques :  6198
Value_counts :
 NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                       

In [665]:
# Renaming the comfort_&_convenience column as comfort_convenience

df.rename(columns={"comfort_&_convenience":"comfort_convenience"}, inplace=True)

In [666]:
# Null values will be worked in next notebook.

### entertainment_&_media column

In [667]:
# Checking the entertainment_&_media column

first_look("entertainment_&_media")

column name :  entertainment_&_media
--------------------------------
Percent_of_Nulls   :  % 8.63
Number_of_Nulls   :  1374
Number_of_Uniques :  346
Value_counts :
 NaN                                                                                                 1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                          1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                       982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                             783
On-board computer,Radio                                                                              487
                                                                                                    ... 
Bluetooth,CD player,Digital radio,Hands-free equipment,Radio                                           1
CD player,Hands-free equipment,MP3,Radio,USB                                                       

In [668]:
# Renaming the entertainment_&_media column as entertainment_media

df.rename(columns={"entertainment_&_media":"entertainment_media"}, inplace=True)

In [669]:
# Null values will be worked in next notebook.

### extras column 

In [670]:
# Checking the extras column

first_look("extras")

column name :  extras
--------------------------------
Percent_of_Nulls   :  % 18.61
Number_of_Nulls   :  2962
Number_of_Uniques :  659
Value_counts :
 Alloy wheels                                                                                               3245
NaN                                                                                                        2962
Alloy wheels,Touch screen                                                                                   697
Alloy wheels,Voice Control                                                                                  577
Alloy wheels,Touch screen,Voice Control                                                                     541
                                                                                                           ... 
Alloy wheels,Catalytic Converter,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control       1
Alloy wheels,Catalytic Converter,Roof rack,Sport package,Sport s

In [671]:
# Null values will be worked in next notebook.

### safety_&_security column

In [672]:
# Checking the safety_&_security column

first_look("safety_&_security")

column name :  safety_&_security
--------------------------------
Percent_of_Nulls   :  % 6.17
Number_of_Nulls   :  982
Number_of_Uniques :  4443
Value_counts :
 NaN                                                                                                                                                                                                                                                                                                                                                               982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                      538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-

In [673]:
# Renaming the safety_&_security column as safety_security

df.rename(columns={"safety_&_security":"safety_security"}, inplace=True)

In [674]:
# Null values will be worked in next notebook.

### description column

In [675]:
# Checking the description column

first_look("description")

column name :  description
--------------------------------
Percent_of_Nulls   :  % 4.19
Number_of_Nulls   :  667
Number_of_Uniques :  12863
Value_counts :
 NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [676]:
# As description column doesn't contain usefull information and it is not related with price,
# it was decide to drop description column

df.drop(columns="description", inplace=True)

In [677]:
df.shape

(15919, 45)

### emission_label column

In [678]:
# Checking the emission_label column

first_look("emission_label")

column name :  emission_label
--------------------------------
Percent_of_Nulls   :  % 75.22
Number_of_Nulls   :  11974
Number_of_Uniques :  5
Value_counts :
 NaN               11974
4 (Green)          3553
1 (No sticker)      381
5 (Blue)              8
3 (Yellow)            2
2 (Red)               1
Name: emission_label, dtype: int64

Value_counts with sort index :
 1 (No sticker)      381
2 (Red)               1
3 (Yellow)            2
4 (Green)          3553
5 (Blue)              8
NaN               11974
Name: emission_label, dtype: int64
########################################



In [679]:
# As it contains so many null values and it is not possible to fill null values in this column
# from other columns, it was decided to drop emission_label column.

df.drop(columns="emission_label", inplace=True)

In [680]:
df.shape

(15919, 44)

### gears columns

In [681]:
# Checking the gears column

first_look("gears")

column name :  gears
--------------------------------
Percent_of_Nulls   :  % 29.6
Number_of_Nulls   :  4712
Number_of_Uniques :  10
Value_counts :
 6      5822
NaN    4712
5      3239
7      1908
8       224
9         6
1         2
3         2
4         2
2         1
50        1
Name: gears, dtype: int64

Value_counts with sort index :
 1         2
2         1
3         2
4         2
5      3239
50        1
6      5822
7      1908
8       224
9         6
NaN    4712
Name: gears, dtype: int64
########################################



In [682]:
# Fixing data type

df["gears"] =  df.gears.astype(float)

In [683]:
# Null values will be worked in next notebook.

### country_version column

In [684]:
# Checking the country_version column

first_look("country_version")

column name :  country_version
--------------------------------
Percent_of_Nulls   :  % 52.35
Number_of_Nulls   :  8333
Number_of_Uniques :  23
Value_counts :
 NaN               8333
Germany           4502
Italy             1038
European Union     507
Netherlands        464
Spain              325
Belgium            314
Austria            208
Czech Republic      52
Poland              49
France              38
Denmark             33
Hungary             28
Japan                8
Slovakia             4
Croatia              4
Sweden               3
Romania              2
Bulgaria             2
Luxembourg           1
Switzerland          1
Slovenia             1
Egypt                1
Serbia               1
Name: country_version, dtype: int64

Value_counts with sort index :
 Austria            208
Belgium            314
Bulgaria             2
Croatia              4
Czech Republic      52
Denmark             33
Egypt                1
European Union     507
France              38
Germany     

In [685]:
df.groupby("country_version").price.mean()

country_version
Austria           20394.120192
Belgium           17485.684713
Bulgaria          17593.000000
Croatia           15179.750000
Czech Republic    23551.057692
Denmark           22587.606061
Egypt             16990.000000
European Union    20291.230769
France            14952.315789
Germany           18362.484896
Hungary           21490.285714
Italy             17140.421965
Japan             13343.000000
Luxembourg        14200.000000
Netherlands       25996.476293
Poland            20071.163265
Romania           19714.000000
Serbia             8490.000000
Slovakia          24612.500000
Slovenia          20985.000000
Spain             15077.224615
Sweden            20837.666667
Switzerland       16999.000000
Name: price, dtype: float64

In [686]:
# drop country_version column as it contains so many null values and
# other values in this column doesn't related with price.

df.drop(columns="country_version", inplace=True)

In [687]:
df.shape

(15919, 43)

## Conclusion after cleaning process

At the begining of the cleaning process firstly we made a general cleanin in dataframe. And then we cleaned columns one by one. During this process necessary values were taken from columns, and unnecessary columns was dropped. Finally cleaned dataframe was saved as "scout_car_cleaned.csv".

Handling with null values process will be worked in another notebook.

## Saving cleaned df as "scout_car_cleaned.csv"

In [688]:
df.to_csv("scout_car_cleaned.csv", index=False)

In [689]:
pd.read_csv("scout_car_cleaned.csv")

url      make_model  \
0      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
1      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
2      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
3      https://www.autoscout24.com//offers/audi-a1-1-...         Audi A1   
4      https://www.autoscout24.com//offers/audi-a1-sp...         Audi A1   
...                                                  ...             ...   
15914  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15915  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15916  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15917  https://www.autoscout24.com//offers/renault-es...  Renault Espace   
15918  https://www.autoscout24.com//offers/renault-es...  Renault Espace   

                                       short_description body_type    price  \
0            Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770.0   
1                                         1.8 TFSI sport    Sedans  14500.0   
2      Sportback 1.6 TDI S tronic Einparkhilfe plus+m...    Sedans  14640.0   
3                                1.4 TDi Design S tronic    Sedans  14500.0   
4      Sportback 1.4 TDI S-Tronic S-Line Ext. admired...    Sedans  16790.0   
...                                                  ...       ...      ...   
15914              Blue dCi 200CV EDC Executive 4Control       Van  39950.0   
15915                TCe 225 EDC GPF LIM Deluxe Pano,RFK       Van  39885.0   
15916  Blue dCi 200 EDC Initiale Paris Leder LED Navi...       Van  39875.0   
15917  Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...       Van  39700.0   
15918        INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX       Van  40999.0   

                    vat       km  prev_owner            type  \
0        VAT deductible  56013.0         2.0            Used   
1      Price negotiable  80000.0         NaN            Used   
2        VAT deductible  83450.0         1.0            Used   
3                   NaN  73000.0         1.0            Used   
4                   NaN  16200.0         1.0            Used   
...                 ...      ...         ...             ...   
15914    VAT deductible      NaN         NaN             New   
15915    VAT deductible   9900.0         1.0            Used   
15916    VAT deductible     15.0         1.0  Pre-registered   
15917    VAT deductible     10.0         NaN  Pre-registered   
15918    VAT deductible      NaN         1.0   Demonstration   

                                         previous_owners  \
0                                                      2   
1                                                    NaN   
2                                                      1   
3                                                      1   
4                                                      1   
...                                                  ...   
15914                                                NaN   
15915  1,,7.4 l/100 km (comb),,9.2 l/100 km (city),,6...   
15916                              1,139 g CO2/km (comb)   
15917                                                NaN   
15918                                                  1   

                   next_inspection           inspection_new  \
0       06/2021,99 g CO2/km (comb)               Yes,Euro 6   
1                              NaN                      NaN   
2                              NaN                      NaN   
3                              NaN                      NaN   
4                              NaN  Yes,109 g CO2/km (comb)   
...                            ...                      ...   
15914                          NaN                      NaN   
15915  01/2022,168 g CO2/km (comb)                      NaN   
15916                          NaN         Yes,Euro 6d-TEMP   
15917                          NaN                      NaN   
15918   