CREATE DATABASE MANUFACTURER;

USE MANUFACTURER

--Create three shcemas

CREATE SCHEMA PRODUCT;
CREATE SCHEMA COMPONENT;
CREATE SCHEMA SUPLIER;

--Create PRODUCT.PRODUCT Table
CREATE TABLE [PRODUCT].[PRODUCT](
	[Prod_ID] [INT] PRIMARY KEY NOT NULL,
	[Prod_Name] [VARCHAR](50) NOT NULL,
	[quantity] [INT] NULL)


--Create PRODUCT.PRODUCT_COMP Table

CREATE TABLE [PRODUCT].[PRODUCT_COMP](
	[Prod_ID] [INT] NOT NULL,
	[Comp_ID] [INT] NOT NULL,
	[quantity_comp] INT NULL,
	PRIMARY KEY ([Prod_ID], [Comp_ID]))


--Create COMPONENT.COMPONENT Table

CREATE TABLE [COMPONENT].[COMPONENT](
	[Comp_ID] [INT] PRIMARY KEY NOT NULL,
	[Comp_Name] [VARCHAR](50) NULL,
	[Description] [VARCHAR](50) NULL,
	[quantity_comp] INT NULL)


--Create COMPONENT.COMP_SUPP Table

CREATE TABLE [COMPONENT].[COMP_SUPP](
	[Supp_ID][INT] NOT NULL,
	[Comp_ID][INT] NOT NULL,
	[Order_date][DATE] NOT NULL,
	[quantity] [INT] NULL,
	PRIMARY KEY([Supp_ID], [Comp_ID]))

-- Create SUPLIER.SUPLIER Table

CREATE TABLE [SUPLIER].[SUPLIER](
	[Supp_ID][INT] PRIMARY KEY NOT NULL,
	[Supp_name] VARCHAR(50) NULL,
	[Supp_location] VARCHAR(50) NULL,
	[Supp_country] VARCHAR(50) NULL,
	[is_active] BIT NULL)

-- Adding Foreign Key constraints

ALTER TABLE [PRODUCT].[PRODUCT_COMP] ADD CONSTRAINT FK_Product
FOREIGN KEY (Prod_ID) REFERENCES PRODUCT.PRODUCT (Prod_ID)

ALTER TABLE [PRODUCT].[PRODUCT_COMP] ADD CONSTRAINT FK_Compound
FOREIGN KEY (Comp_ID) REFERENCES COMPONENT.COMPONENT (Comp_ID)

ALTER TABLE [COMPONENT].[COMP_SUPP] ADD CONSTRAINT FK_Supplier
FOREIGN KEY (Supp_ID) REFERENCES [SUPLIER].[SUPLIER] (Supp_ID)

ALTER TABLE [COMPONENT].[COMP_SUPP] ADD CONSTRAINT FK_Component
FOREIGN KEY (Comp_ID) REFERENCES COMPONENT.COMPONENT (Comp_ID)
